# docker-compose.yml

version: "3.7"

services:
    huddle-db:
        image: postgres:latest
        restart: on-failure
        container_name: huddle-db
        environment:
            POSTGRES_DB: huddledevdb
            POSTGRES_USER: huddle
            POSTGRES_PASSWORD: huddle
        volumes:
            - huddle-pgdata:/var/lib/postgresql/data
        logging:
            driver: json-file
        ports:
            - 8001:5432

    huddle-redis:
        image: redis
        container_name: huddle-cache
        logging:
            driver: json-file
        ports:
            - 6379:6379

    huddle-loki:
        image: grafana/loki:latest
        container_name: huddle-loki
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml

    huddle-promtail:
        image: grafana/promtail:latest
        container_name: huddle-promtail
        volumes:
            - huddle-promtaildata:/var/log
        command: -config.file=/etc/promtail/docker-config.yaml

    huddle-grafana:
        image: grafana/grafana:master
        container_name: huddle-grafana
        ports:
            - "3200:3000"

volumes:
    huddle-pgdata:
    huddle-promtaildata:
