version: '3.7'

services:
  huddle-db:
    image: postgres:latest
    restart: on-failure
    container_name: huddle-db
    environment:
      POSTGRES_DB: huddletestdb
      POSTGRES_USER: huddle
      POSTGRES_PASSWORD: huddle
    logging:
      driver: json-file
    ports:
      - 8001:5432

  huddle-redis:
    image: redis
    container_name: huddle-cache
    logging:
      driver: json-file
    ports:
      - 6379:6379