/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
    /**
     * A country code as defined by ISO 3166-1 alpha-2
     */
    countryCode<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "CountryCode";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "EmailAddress";
    /**
     * A field whose value conforms to the standard E.164 format as specified in: https://en.wikipedia.org/wiki/E.164. Basically this is +17895551234.
     */
    phone<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "PhoneNumber";
    /**
     * A field whose value is a JSON Web Token (JWT): https://jwt.io/introduction.
     */
    jwt<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JWT";
    /**
     * The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSON";
    /**
     * A field whose value is a IPv4 address: https://en.wikipedia.org/wiki/IPv4.
     */
    ipv4<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "IPv4";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
    /**
     * A country code as defined by ISO 3166-1 alpha-2
     */
    countryCode<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "CountryCode";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "EmailAddress";
    /**
     * A field whose value conforms to the standard E.164 format as specified in: https://en.wikipedia.org/wiki/E.164. Basically this is +17895551234.
     */
    phone<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "PhoneNumber";
    /**
     * A field whose value is a JSON Web Token (JWT): https://jwt.io/introduction.
     */
    jwt<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JWT";
    /**
     * The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSON";
    /**
     * A field whose value is a IPv4 address: https://en.wikipedia.org/wiki/IPv4.
     */
    ipv4<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "IPv4";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  LoginInput: { // input type
    emailOrUsername: string; // String!
    ip?: NexusGenScalars['IPv4'] | null; // IPv4
    password: string; // String!
  }
  PlayerPredictionInput: { // input type
    code: string; // String!
    type: string; // String!
    value?: NexusGenScalars['JSON'] | null; // JSON
  }
  PredictionInput: { // input type
    matchId: string; // String!
    predictionId?: string | null; // String
    predictions: Array<NexusGenInputs['PlayerPredictionInput'] | null>; // [PlayerPredictionInput]!
  }
  UpdateRoomInput: { // input type
    description?: string | null; // String
    name?: string | null; // String
    roomId: string; // String!
  }
  UpdateUserProfileInput: { // input type
    country?: string | null; // String
    favoriteTeam?: string | null; // String
    firstname?: string | null; // String
    lastname?: string | null; // String
    onboarded?: boolean | null; // Boolean
    phone?: string | null; // String
    profileColour?: string | null; // String
    username?: string | null; // String
  }
}

export interface NexusGenEnums {
  ChatUserRoleType: "admin" | "channel_member" | "channel_moderator" | "user"
  GameStatus: "completed" | "in_progress"
  GameType: "season" | "weekly"
  RoomType: "private" | "public"
  sort: "ASC" | "DESC"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  CountryCode: any
  DateTime: any
  EmailAddress: any
  IPv4: any
  JSON: any
  JWT: any
  PhoneNumber: any
}

export interface NexusGenObjects {
  AuthOutput: { // root type
    accessToken?: string | null; // String
    message: string; // String!
    refreshToken?: string | null; // String
    user: NexusGenRootTypes['User']; // User!
  }
  ChatData: { // root type
    streamUserId: string; // String!
    token?: string | null; // String
  }
  CheckUsernameOutput: { // root type
    available: boolean; // Boolean!
    message: string; // String!
  }
  Country: { // root type
    code: string; // String!
    emoji: string; // String!
    name: string; // String!
  }
  CreateRoomOutput: { // root type
    message: string; // String!
    room: NexusGenRootTypes['Room']; // Room!
  }
  Cursor: { // root type
    next?: string | null; // String
    prev?: string | null; // String
  }
  GamePlayer: { // root type
    displayName: string; // String!
    playerId: string; // ID!
    score: number; // Float!
    username: string; // String!
  }
  Match: { // root type
    dateTime: NexusGenScalars['DateTime']; // DateTime!
    id?: string | null; // ID
    misc?: NexusGenScalars['JSON'] | null; // JSON
    periods: NexusGenRootTypes['MatchPeriod']; // MatchPeriod!
    questions?: Array<NexusGenRootTypes['Prediction'] | null> | null; // [Prediction]
    scores?: NexusGenScalars['JSON'] | null; // JSON
    season: string; // String!
    status: NexusGenRootTypes['MatchStatus']; // MatchStatus!
    teams: NexusGenRootTypes['TeamData']; // TeamData!
    venue?: string | null; // String
    winner?: string | null; // String
  }
  MatchPeriod: { // root type
    first?: NexusGenScalars['DateTime'] | null; // DateTime
    firstExtra?: NexusGenScalars['DateTime'] | null; // DateTime
    penalties?: NexusGenScalars['DateTime'] | null; // DateTime
    second?: NexusGenScalars['DateTime'] | null; // DateTime
    secondExtra?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  MatchPrediction: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // ID!
    matchId: string; // String!
    predictions: Array<NexusGenRootTypes['Prediction'] | null>; // [Prediction]!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  MatchStatistic: { // root type
    type?: string | null; // String
    value?: string | null; // String
  }
  MatchStatus: { // root type
    long?: string | null; // String
    short?: string | null; // String
    timeElapsed?: number | null; // Int
  }
  Mutation: {};
  Pagination: { // root type
    limit?: number | null; // Int
    page?: number | null; // Int
    pages?: number | null; // Int
    total?: number | null; // Int
  }
  Prediction: { // root type
    code: string; // String!
    options?: Array<NexusGenRootTypes['PredictionOption'] | null> | null; // [PredictionOption]
    points?: number | null; // Int
    question?: string | null; // String
    solution?: NexusGenScalars['JSON'] | null; // JSON
    type: string; // String!
    value?: NexusGenScalars['JSON'] | null; // JSON
  }
  PredictionOption: { // root type
    display?: string | null; // String
    value?: string | null; // String
  }
  PredictionOutput: { // root type
    message: string; // String!
    prediction: NexusGenRootTypes['MatchPrediction']; // MatchPrediction!
  }
  Query: {};
  Room: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    games?: Array<NexusGenRootTypes['RoomGame'] | null> | null; // [RoomGame]
    id: string; // ID!
    joiningFee: number; // Float!
    name: string; // String!
    roomImageUrl?: string | null; // String
    roomType: NexusGenEnums['RoomType']; // RoomType!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  RoomGame: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    expiringAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // ID!
    leaderBoard: Array<NexusGenRootTypes['GamePlayer'] | null>; // [GamePlayer]!
    name: string; // String!
    roomId: string; // ID!
    status: NexusGenEnums['GameStatus']; // GameStatus!
    summary: NexusGenScalars['JSON']; // JSON!
    type: NexusGenEnums['GameType']; // GameType!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    winnerId?: string | null; // ID
  }
  Team: { // root type
    code: string; // String!
    id: string; // ID!
    logo: string; // String!
    name: string; // String!
    score?: string | null; // String
    stadium?: string | null; // String
    statistics?: Array<NexusGenRootTypes['MatchStatistic'] | null> | null; // [MatchStatistic]
    winner?: boolean | null; // Boolean
  }
  TeamData: { // root type
    away?: NexusGenRootTypes['Team'] | null; // Team
    home?: NexusGenRootTypes['Team'] | null; // Team
  }
  TokenSendOutput: { // root type
    message: string; // String!
    sent: boolean; // Boolean!
  }
  UpdateUserProfileOutput: { // root type
    message: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // root type
    chatData?: NexusGenRootTypes['ChatData'] | null; // ChatData
    coinBalance: number; // Float!
    country?: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: NexusGenScalars['EmailAddress']; // EmailAddress!
    emailVerified: boolean; // Boolean!
    favoriteTeam?: string | null; // String
    firstname?: string | null; // String
    gamesSummary?: NexusGenScalars['JSON'] | null; // JSON
    lastname?: string | null; // String
    onboarded: boolean; // Boolean!
    phone?: NexusGenScalars['PhoneNumber'] | null; // PhoneNumber
    profileColour: string; // String!
    profileImageUrl: string; // String!
    referralCode: string; // String!
    referralCount: number; // Int!
    roles: Array<string | null>; // [String]!
    settings?: NexusGenScalars['JSON'] | null; // JSON
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    userId: string; // ID!
    userState: string; // String!
    username?: string | null; // String
  }
}

export interface NexusGenInterfaces {
  CursorPaginationOutput: any;
  MutationOutput: NexusGenRootTypes['AuthOutput'] | NexusGenRootTypes['CheckUsernameOutput'] | NexusGenRootTypes['CreateRoomOutput'] | NexusGenRootTypes['PredictionOutput'] | NexusGenRootTypes['TokenSendOutput'] | NexusGenRootTypes['UpdateUserProfileOutput'];
  PaginatedInput: any;
  PaginationOutput: any;
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthOutput: { // field return type
    accessToken: string | null; // String
    message: string; // String!
    refreshToken: string | null; // String
    user: NexusGenRootTypes['User']; // User!
  }
  ChatData: { // field return type
    streamUserId: string; // String!
    token: string | null; // String
  }
  CheckUsernameOutput: { // field return type
    available: boolean; // Boolean!
    message: string; // String!
  }
  Country: { // field return type
    code: string; // String!
    emoji: string; // String!
    name: string; // String!
  }
  CreateRoomOutput: { // field return type
    message: string; // String!
    room: NexusGenRootTypes['Room']; // Room!
  }
  Cursor: { // field return type
    next: string | null; // String
    prev: string | null; // String
  }
  GamePlayer: { // field return type
    displayName: string; // String!
    playerId: string; // ID!
    score: number; // Float!
    username: string; // String!
  }
  Match: { // field return type
    dateTime: NexusGenScalars['DateTime']; // DateTime!
    id: string | null; // ID
    misc: NexusGenScalars['JSON'] | null; // JSON
    periods: NexusGenRootTypes['MatchPeriod']; // MatchPeriod!
    questions: Array<NexusGenRootTypes['Prediction'] | null> | null; // [Prediction]
    scores: NexusGenScalars['JSON'] | null; // JSON
    season: string; // String!
    status: NexusGenRootTypes['MatchStatus']; // MatchStatus!
    teams: NexusGenRootTypes['TeamData']; // TeamData!
    venue: string | null; // String
    winner: string | null; // String
  }
  MatchPeriod: { // field return type
    first: NexusGenScalars['DateTime'] | null; // DateTime
    firstExtra: NexusGenScalars['DateTime'] | null; // DateTime
    penalties: NexusGenScalars['DateTime'] | null; // DateTime
    second: NexusGenScalars['DateTime'] | null; // DateTime
    secondExtra: NexusGenScalars['DateTime'] | null; // DateTime
  }
  MatchPrediction: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // ID!
    matchId: string; // String!
    predictions: Array<NexusGenRootTypes['Prediction'] | null>; // [Prediction]!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  MatchStatistic: { // field return type
    type: string | null; // String
    value: string | null; // String
  }
  MatchStatus: { // field return type
    long: string | null; // String
    short: string | null; // String
    timeElapsed: number | null; // Int
  }
  Mutation: { // field return type
    changePassword: NexusGenRootTypes['AuthOutput']; // AuthOutput!
    checkUsername: NexusGenRootTypes['CheckUsernameOutput']; // CheckUsernameOutput!
    createRoom: NexusGenRootTypes['CreateRoomOutput']; // CreateRoomOutput!
    joinRoom: NexusGenRootTypes['CreateRoomOutput']; // CreateRoomOutput!
    login: NexusGenRootTypes['AuthOutput']; // AuthOutput!
    logout: boolean; // Boolean!
    predictMatch: NexusGenRootTypes['PredictionOutput']; // PredictionOutput!
    resetPassword: NexusGenRootTypes['AuthOutput']; // AuthOutput!
    sendEmailVerification: NexusGenRootTypes['TokenSendOutput']; // TokenSendOutput!
    sendPasswordReset: NexusGenRootTypes['TokenSendOutput']; // TokenSendOutput!
    signup: NexusGenRootTypes['AuthOutput']; // AuthOutput!
    syncFirebaseUser: NexusGenRootTypes['AuthOutput']; // AuthOutput!
    updateChatUserRole: NexusGenRootTypes['CreateRoomOutput']; // CreateRoomOutput!
    updatePrediction: NexusGenRootTypes['PredictionOutput']; // PredictionOutput!
    updateRoom: NexusGenRootTypes['CreateRoomOutput']; // CreateRoomOutput!
    updateUserProfile: NexusGenRootTypes['UpdateUserProfileOutput']; // UpdateUserProfileOutput!
    verifyEmail: NexusGenRootTypes['AuthOutput']; // AuthOutput!
  }
  Pagination: { // field return type
    limit: number | null; // Int
    page: number | null; // Int
    pages: number | null; // Int
    total: number | null; // Int
  }
  Prediction: { // field return type
    code: string; // String!
    options: Array<NexusGenRootTypes['PredictionOption'] | null> | null; // [PredictionOption]
    points: number | null; // Int
    question: string | null; // String
    solution: NexusGenScalars['JSON'] | null; // JSON
    type: string; // String!
    value: NexusGenScalars['JSON'] | null; // JSON
  }
  PredictionOption: { // field return type
    display: string | null; // String
    value: string | null; // String
  }
  PredictionOutput: { // field return type
    message: string; // String!
    prediction: NexusGenRootTypes['MatchPrediction']; // MatchPrediction!
  }
  Query: { // field return type
    countries: Array<NexusGenRootTypes['Country'] | null>; // [Country]!
    fixtures: NexusGenRootTypes['Match'][]; // [Match!]!
    room: NexusGenRootTypes['Room']; // Room!
    teams: Array<NexusGenRootTypes['Team'] | null>; // [Team]!
    viewer: NexusGenRootTypes['User']; // User!
  }
  Room: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    games: Array<NexusGenRootTypes['RoomGame'] | null> | null; // [RoomGame]
    id: string; // ID!
    joiningFee: number; // Float!
    name: string; // String!
    roomImageUrl: string | null; // String
    roomType: NexusGenEnums['RoomType']; // RoomType!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  RoomGame: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string | null; // String
    expiringAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string; // ID!
    leaderBoard: Array<NexusGenRootTypes['GamePlayer'] | null>; // [GamePlayer]!
    name: string; // String!
    roomId: string; // ID!
    status: NexusGenEnums['GameStatus']; // GameStatus!
    summary: NexusGenScalars['JSON']; // JSON!
    type: NexusGenEnums['GameType']; // GameType!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    winnerId: string | null; // ID
  }
  Team: { // field return type
    code: string; // String!
    id: string; // ID!
    logo: string; // String!
    name: string; // String!
    score: string | null; // String
    stadium: string | null; // String
    statistics: Array<NexusGenRootTypes['MatchStatistic'] | null> | null; // [MatchStatistic]
    winner: boolean | null; // Boolean
  }
  TeamData: { // field return type
    away: NexusGenRootTypes['Team'] | null; // Team
    home: NexusGenRootTypes['Team'] | null; // Team
  }
  TokenSendOutput: { // field return type
    message: string; // String!
    sent: boolean; // Boolean!
  }
  UpdateUserProfileOutput: { // field return type
    message: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // field return type
    chatData: NexusGenRootTypes['ChatData'] | null; // ChatData
    coinBalance: number; // Float!
    country: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: NexusGenScalars['EmailAddress']; // EmailAddress!
    emailVerified: boolean; // Boolean!
    favoriteTeam: string | null; // String
    firstname: string | null; // String
    gamesSummary: NexusGenScalars['JSON'] | null; // JSON
    lastname: string | null; // String
    onboarded: boolean; // Boolean!
    phone: NexusGenScalars['PhoneNumber'] | null; // PhoneNumber
    profileColour: string; // String!
    profileImageUrl: string; // String!
    referralCode: string; // String!
    referralCount: number; // Int!
    roles: Array<string | null>; // [String]!
    settings: NexusGenScalars['JSON'] | null; // JSON
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    userId: string; // ID!
    userState: string; // String!
    username: string | null; // String
  }
  CursorPaginationOutput: { // field return type
    cursor: NexusGenRootTypes['Cursor']; // Cursor!
  }
  MutationOutput: { // field return type
    message: string; // String!
  }
  PaginatedInput: { // field return type
    limit: number | null; // Int
    page: number | null; // Int
  }
  PaginationOutput: { // field return type
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
}

export interface NexusGenFieldTypeNames {
  AuthOutput: { // field return type name
    accessToken: 'String'
    message: 'String'
    refreshToken: 'String'
    user: 'User'
  }
  ChatData: { // field return type name
    streamUserId: 'String'
    token: 'String'
  }
  CheckUsernameOutput: { // field return type name
    available: 'Boolean'
    message: 'String'
  }
  Country: { // field return type name
    code: 'String'
    emoji: 'String'
    name: 'String'
  }
  CreateRoomOutput: { // field return type name
    message: 'String'
    room: 'Room'
  }
  Cursor: { // field return type name
    next: 'String'
    prev: 'String'
  }
  GamePlayer: { // field return type name
    displayName: 'String'
    playerId: 'ID'
    score: 'Float'
    username: 'String'
  }
  Match: { // field return type name
    dateTime: 'DateTime'
    id: 'ID'
    misc: 'JSON'
    periods: 'MatchPeriod'
    questions: 'Prediction'
    scores: 'JSON'
    season: 'String'
    status: 'MatchStatus'
    teams: 'TeamData'
    venue: 'String'
    winner: 'String'
  }
  MatchPeriod: { // field return type name
    first: 'DateTime'
    firstExtra: 'DateTime'
    penalties: 'DateTime'
    second: 'DateTime'
    secondExtra: 'DateTime'
  }
  MatchPrediction: { // field return type name
    createdAt: 'DateTime'
    id: 'ID'
    matchId: 'String'
    predictions: 'Prediction'
    updatedAt: 'DateTime'
  }
  MatchStatistic: { // field return type name
    type: 'String'
    value: 'String'
  }
  MatchStatus: { // field return type name
    long: 'String'
    short: 'String'
    timeElapsed: 'Int'
  }
  Mutation: { // field return type name
    changePassword: 'AuthOutput'
    checkUsername: 'CheckUsernameOutput'
    createRoom: 'CreateRoomOutput'
    joinRoom: 'CreateRoomOutput'
    login: 'AuthOutput'
    logout: 'Boolean'
    predictMatch: 'PredictionOutput'
    resetPassword: 'AuthOutput'
    sendEmailVerification: 'TokenSendOutput'
    sendPasswordReset: 'TokenSendOutput'
    signup: 'AuthOutput'
    syncFirebaseUser: 'AuthOutput'
    updateChatUserRole: 'CreateRoomOutput'
    updatePrediction: 'PredictionOutput'
    updateRoom: 'CreateRoomOutput'
    updateUserProfile: 'UpdateUserProfileOutput'
    verifyEmail: 'AuthOutput'
  }
  Pagination: { // field return type name
    limit: 'Int'
    page: 'Int'
    pages: 'Int'
    total: 'Int'
  }
  Prediction: { // field return type name
    code: 'String'
    options: 'PredictionOption'
    points: 'Int'
    question: 'String'
    solution: 'JSON'
    type: 'String'
    value: 'JSON'
  }
  PredictionOption: { // field return type name
    display: 'String'
    value: 'String'
  }
  PredictionOutput: { // field return type name
    message: 'String'
    prediction: 'MatchPrediction'
  }
  Query: { // field return type name
    countries: 'Country'
    fixtures: 'Match'
    room: 'Room'
    teams: 'Team'
    viewer: 'User'
  }
  Room: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    games: 'RoomGame'
    id: 'ID'
    joiningFee: 'Float'
    name: 'String'
    roomImageUrl: 'String'
    roomType: 'RoomType'
    updatedAt: 'DateTime'
  }
  RoomGame: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    expiringAt: 'DateTime'
    id: 'ID'
    leaderBoard: 'GamePlayer'
    name: 'String'
    roomId: 'ID'
    status: 'GameStatus'
    summary: 'JSON'
    type: 'GameType'
    updatedAt: 'DateTime'
    winnerId: 'ID'
  }
  Team: { // field return type name
    code: 'String'
    id: 'ID'
    logo: 'String'
    name: 'String'
    score: 'String'
    stadium: 'String'
    statistics: 'MatchStatistic'
    winner: 'Boolean'
  }
  TeamData: { // field return type name
    away: 'Team'
    home: 'Team'
  }
  TokenSendOutput: { // field return type name
    message: 'String'
    sent: 'Boolean'
  }
  UpdateUserProfileOutput: { // field return type name
    message: 'String'
    user: 'User'
  }
  User: { // field return type name
    chatData: 'ChatData'
    coinBalance: 'Float'
    country: 'String'
    createdAt: 'DateTime'
    email: 'EmailAddress'
    emailVerified: 'Boolean'
    favoriteTeam: 'String'
    firstname: 'String'
    gamesSummary: 'JSON'
    lastname: 'String'
    onboarded: 'Boolean'
    phone: 'PhoneNumber'
    profileColour: 'String'
    profileImageUrl: 'String'
    referralCode: 'String'
    referralCount: 'Int'
    roles: 'String'
    settings: 'JSON'
    updatedAt: 'DateTime'
    userId: 'ID'
    userState: 'String'
    username: 'String'
  }
  CursorPaginationOutput: { // field return type name
    cursor: 'Cursor'
  }
  MutationOutput: { // field return type name
    message: 'String'
  }
  PaginatedInput: { // field return type name
    limit: 'Int'
    page: 'Int'
  }
  PaginationOutput: { // field return type name
    pagination: 'Pagination'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    changePassword: { // args
      newPassword: string; // String!
      oldPassword?: string | null; // String
    }
    checkUsername: { // args
      username: string; // String!
    }
    createRoom: { // args
      description?: string | null; // String
      name: string; // String!
      roomType?: string | null; // String
    }
    joinRoom: { // args
      roomId: string; // String!
    }
    login: { // args
      input: NexusGenInputs['LoginInput']; // LoginInput!
    }
    predictMatch: { // args
      input: NexusGenInputs['PredictionInput']; // PredictionInput!
    }
    resetPassword: { // args
      password: string; // String!
      token: string; // String!
      userId: string; // String!
    }
    sendEmailVerification: { // args
      email: string; // String!
    }
    sendPasswordReset: { // args
      email: string; // String!
    }
    signup: { // args
      email: string; // String!
      password?: string | null; // String
      referralCode?: string | null; // String
    }
    syncFirebaseUser: { // args
      referralCode?: string | null; // String
      token: string; // String!
    }
    updateChatUserRole: { // args
      role: NexusGenEnums['ChatUserRoleType']; // ChatUserRoleType!
      roomId: string; // String!
    }
    updatePrediction: { // args
      input: NexusGenInputs['PredictionInput']; // PredictionInput!
    }
    updateRoom: { // args
      input: NexusGenInputs['UpdateRoomInput']; // UpdateRoomInput!
    }
    updateUserProfile: { // args
      input: NexusGenInputs['UpdateUserProfileInput']; // UpdateUserProfileInput!
    }
    verifyEmail: { // args
      token: string; // String!
    }
  }
  Query: {
    fixtures: { // args
      date?: string | null; // String
      live?: boolean | null; // Boolean
    }
    room: { // args
      roomId: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  MutationOutput: "AuthOutput" | "CheckUsernameOutput" | "CreateRoomOutput" | "PredictionOutput" | "TokenSendOutput" | "UpdateUserProfileOutput"
}

export interface NexusGenTypeInterfaces {
  AuthOutput: "MutationOutput"
  CheckUsernameOutput: "MutationOutput"
  CreateRoomOutput: "MutationOutput"
  PredictionOutput: "MutationOutput"
  TokenSendOutput: "MutationOutput"
  UpdateUserProfileOutput: "MutationOutput"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    resolveType: false
    __typename: false
    isTypeOf: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}