const livAthletes = [
    {
        player: {
            id: 280,
            name: "Alisson Ramsés Becker",
            firstname: "Alisson Ramsés",
            lastname: "Becker",
            age: 30,
            birth: {
                date: "1992-10-02",
                place: "Novo Hamburgo",
                country: "Brazil",
            },
            nationality: "Brazil",
            height: "193 cm",
            weight: "91 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/280.png",
        },
    },
    {
        player: {
            id: 284,
            name: "J. Gomez",
            firstname: "Joe",
            lastname: "Gomez",
            age: 25,
            birth: {
                date: "1997-05-23",
                place: "London",
                country: "England",
            },
            nationality: "England",
            height: "188 cm",
            weight: "77 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/284.png",
        },
    },
    {
        player: {
            id: 286,
            name: "Joël Andre Job Matip",
            firstname: "Joël Andre",
            lastname: "Job Matip",
            age: 31,
            birth: {
                date: "1991-08-08",
                place: "Bochum",
                country: "Germany",
            },
            nationality: "Cameroon",
            height: "195 cm",
            weight: "90 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/286.png",
        },
    },
    {
        player: {
            id: 301,
            name: "B. Woodburn",
            firstname: "Benjamin Luke",
            lastname: "Woodburn",
            age: 23,
            birth: {
                date: "1999-10-15",
                place: "Nottingham",
                country: "England",
            },
            nationality: "Wales",
            height: "174 cm",
            weight: "72 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/301.png",
        },
    },
    {
        player: {
            id: 1972,
            name: "Loris Karius",
            firstname: "Loris",
            lastname: "Karius",
            age: 29,
            birth: {
                date: "1993-06-22",
                place: "Biberach an der Riß",
                country: "Germany",
            },
            nationality: "Germany",
            height: "189 cm",
            weight: "90 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/1972.png",
        },
    },
    {
        player: {
            id: 8598,
            name: "T. Awoniyi",
            firstname: "Taiwo Micheal",
            lastname: "Awoniyi",
            age: 25,
            birth: {
                date: "1997-08-12",
                place: "Ilorin",
                country: "Nigeria",
            },
            nationality: "Nigeria",
            height: "183 cm",
            weight: "84 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/8598.png",
        },
    },
    {
        player: {
            id: 18812,
            name: "Adrián San Miguel del Castillo",
            firstname: "Adrián",
            lastname: "San Miguel del Castillo",
            age: 35,
            birth: {
                date: "1987-01-03",
                place: "Sevilla",
                country: "Spain",
            },
            nationality: "Spain",
            height: "190 cm",
            weight: "80 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/18812.png",
        },
    },
    {
        player: {
            id: 19437,
            name: "B. Davies",
            firstname: "Ben",
            lastname: "Davies",
            age: 27,
            birth: {
                date: "1995-08-11",
                place: "Barrow",
                country: "England",
            },
            nationality: "England",
            height: "185 cm",
            weight: "74 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/19437.png",
        },
    },
    {
        player: {
            id: 138826,
            name: "Adam Thomas Lewis",
            firstname: "Adam Thomas",
            lastname: "Lewis",
            age: 23,
            birth: {
                date: "1999-11-08",
                place: "Liverpool",
                country: "England",
            },
            nationality: "England",
            height: "175 cm",
            weight: "73 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/138826.png",
        },
    },
    {
        player: {
            id: 151754,
            name: "Leighton Owen Clarkson",
            firstname: "Leighton",
            lastname: "Owen Clarkson",
            age: 21,
            birth: {
                date: "2001-10-19",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: "175 cm",
            weight: "62 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/151754.png",
        },
    },
    {
        player: {
            id: 152974,
            name: "B. Koumetio",
            firstname: "Billy",
            lastname: "Koumetio",
            age: 20,
            birth: {
                date: "2002-11-14",
                place: null,
                country: "France",
            },
            nationality: "France",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/152974.png",
        },
    },
    {
        player: {
            id: 152975,
            name: "Jake Steven Cain",
            firstname: "Jake Steven",
            lastname: "Cain",
            age: 21,
            birth: {
                date: "2001-09-02",
                place: "Wigan",
                country: "England",
            },
            nationality: "England",
            height: "176 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/152975.png",
        },
    },
    {
        player: {
            id: 152979,
            name: "J. Norris",
            firstname: "James",
            lastname: "Norris",
            age: 19,
            birth: {
                date: "2003-04-04",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/152979.png",
        },
    },
    {
        player: {
            id: 158693,
            name: "O. Beck",
            firstname: "Owen",
            lastname: "Beck",
            age: 20,
            birth: {
                date: "2002-08-09",
                place: null,
                country: "Wales",
            },
            nationality: "Wales",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/158693.png",
        },
    },
    {
        player: {
            id: 158698,
            name: "J. Quansah",
            firstname: "Jarell",
            lastname: "Quansah",
            age: 19,
            birth: {
                date: "2003-01-29",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/158698.png",
        },
    },
    {
        player: {
            id: 162441,
            name: "Jakub Ojrzyński",
            firstname: "Jakub",
            lastname: "Ojrzyński",
            age: 19,
            birth: {
                date: "2003-02-19",
                place: null,
                country: "Poland",
            },
            nationality: "Poland",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/162441.png",
        },
    },
    {
        player: {
            id: 162904,
            name: "R. Williams",
            firstname: "Rhys",
            lastname: "Williams",
            age: 21,
            birth: {
                date: "2001-02-03",
                place: "Preston",
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/162904.png",
        },
    },
    {
        player: {
            id: 180316,
            name: "H. Davies",
            firstname: "Harvey",
            lastname: "Davies",
            age: 19,
            birth: {
                date: "2003-09-03",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/180316.png",
        },
    },
    {
        player: {
            id: 180866,
            name: "Marcelo",
            firstname: "Marcelo",
            lastname: "de Araújo Pitaluga Filho",
            age: 20,
            birth: {
                date: "2002-12-20",
                place: "Niterói",
                country: "Brazil",
            },
            nationality: "Brazil",
            height: "191 cm",
            weight: "75 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/180866.png",
        },
    },
    {
        player: {
            id: 314661,
            name: "J. Danns",
            firstname: "Jayden",
            lastname: "Danns",
            age: null,
            birth: {
                date: null,
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/314661.png",
        },
    },
    {
        player: {
            id: 292,
            name: "Jordan Henderson",
            firstname: "Jordan",
            lastname: "Henderson",
            age: 32,
            birth: {
                date: "1990-06-17",
                place: "Sunderland",
                country: "England",
            },
            nationality: "England",
            height: "182 cm",
            weight: "67 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/292.png",
        },
    },
    {
        player: {
            id: 293,
            name: "C. Jones",
            firstname: "Curtis",
            lastname: "Jones",
            age: 21,
            birth: {
                date: "2001-01-30",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: "185 cm",
            weight: "75 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/293.png",
        },
    },
    {
        player: {
            id: 296,
            name: "James Philip Milner",
            firstname: "James Philip",
            lastname: "Milner",
            age: 36,
            birth: {
                date: "1986-01-04",
                place: "Leeds",
                country: "England",
            },
            nationality: "England",
            height: "175 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/296.png",
        },
    },
    {
        player: {
            id: 297,
            name: "Alex Oxlade-Chamberlain",
            firstname: "Alex",
            lastname: "Oxlade-Chamberlain",
            age: 29,
            birth: {
                date: "1993-08-15",
                place: "Portsmouth",
                country: "England",
            },
            nationality: "England",
            height: "180 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/297.png",
        },
    },
    {
        player: {
            id: 299,
            name: "Fabinho",
            firstname: "Fábio Henrique",
            lastname: "Tavares",
            age: 29,
            birth: {
                date: "1993-10-23",
                place: "Campinas",
                country: "Brazil",
            },
            nationality: "Brazil",
            height: "188 cm",
            weight: "78 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/299.png",
        },
    },
    {
        player: {
            id: 302,
            name: "Roberto Firmino Barbosa de Oliveira",
            firstname: "Roberto Firmino",
            lastname: "Barbosa de Oliveira",
            age: 31,
            birth: {
                date: "1991-10-02",
                place: "Maceió",
                country: "Brazil",
            },
            nationality: "Brazil",
            height: "181 cm",
            weight: "76 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/302.png",
        },
    },
    {
        player: {
            id: 305,
            name: "D. Origi",
            firstname: "Divock",
            lastname: "Okoth Origi",
            age: 27,
            birth: {
                date: "1995-04-18",
                place: "Oostende",
                country: "Belgium",
            },
            nationality: "Belgium",
            height: "185 cm",
            weight: "75 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/305.png",
        },
    },
    {
        player: {
            id: 306,
            name: "Mohamed Salah Ghaly",
            firstname: "Mohamed",
            lastname: "Salah Ghaly",
            age: 30,
            birth: {
                date: "1992-06-15",
                place: "Muḥāfaẓat al Gharbiyya",
                country: "Egypt",
            },
            nationality: "Egypt",
            height: "175 cm",
            weight: "71 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/306.png",
        },
    },
    {
        player: {
            id: 507,
            name: "Thiago Alcântara do Nascimento",
            firstname: "Thiago",
            lastname: "Alcântara do Nascimento",
            age: 31,
            birth: {
                date: "1991-04-11",
                place: "San Pietro Vernotico",
                country: "Italy",
            },
            nationality: "Spain",
            height: "174 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/507.png",
        },
    },
    {
        player: {
            id: 1101,
            name: "Takumi Minamino",
            firstname: "Takumi",
            lastname: "Minamino",
            age: 27,
            birth: {
                date: "1995-01-16",
                place: "Osaka",
                country: "Japan",
            },
            nationality: "Japan",
            height: "174 cm",
            weight: "68 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/1101.png",
        },
    },
    {
        player: {
            id: 2489,
            name: "L. Díaz",
            firstname: "Luis Fernando",
            lastname: "Díaz Marulanda",
            age: 25,
            birth: {
                date: "1997-01-13",
                place: "Barrancas",
                country: "Colombia",
            },
            nationality: "Colombia",
            height: "178 cm",
            weight: "65 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/2489.png",
        },
    },
    {
        player: {
            id: 19035,
            name: "H. Elliott",
            firstname: "Harvey",
            lastname: "Elliott",
            age: 19,
            birth: {
                date: "2003-04-04",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: "170 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/19035.png",
        },
    },
    {
        player: {
            id: 138829,
            name: "E. Dixon-Bonner",
            firstname: "Elijah",
            lastname: "Dixon-Bonner",
            age: 21,
            birth: {
                date: "2001-01-01",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/138829.png",
        },
    },
    {
        player: {
            id: 162590,
            name: "T. Morton",
            firstname: "Tyler Scott",
            lastname: "Morton",
            age: 20,
            birth: {
                date: "2002-10-31",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/162590.png",
        },
    },
    {
        player: {
            id: 280683,
            name: "J. Balagizi",
            firstname: "James",
            lastname: "Balagizi",
            age: 19,
            birth: {
                date: "2003-09-20",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/280683.png",
        },
    },
    {
        player: {
            id: 284247,
            name: "H. Blair",
            firstname: "Harvey",
            lastname: "Blair",
            age: 19,
            birth: {
                date: "2003-09-14",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/284247.png",
        },
    },
    {
        player: {
            id: 284248,
            name: "M. Frauendorf",
            firstname: "Melkamu Benjamin Daniel",
            lastname: "Frauendorf",
            age: 18,
            birth: {
                date: "2004-01-12",
                place: null,
                country: "Ethiopia",
            },
            nationality: "Germany",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/284248.png",
        },
    },
    {
        player: {
            id: 284249,
            name: "M. Woltman",
            firstname: "Max",
            lastname: "Woltman",
            age: 19,
            birth: {
                date: "2003-08-20",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/284249.png",
        },
    },
    {
        player: {
            id: 284286,
            name: "I. Mabaya",
            firstname: "Isaac",
            lastname: "Mabaya",
            age: 18,
            birth: {
                date: "2004-09-22",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/284286.png",
        },
    },
    {
        player: {
            id: 286764,
            name: "K. Gordon",
            firstname: "Kaide",
            lastname: "Gordon",
            age: 18,
            birth: {
                date: "2004-10-05",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/286764.png",
        },
    },
    {
        player: {
            id: 281,
            name: "Caoimhin Kelleher",
            firstname: "Caoimhin",
            lastname: "Kelleher",
            age: 24,
            birth: {
                date: "1998-11-23",
                place: "Cork",
                country: "Republic of Ireland",
            },
            nationality: "Republic of Ireland",
            height: "188 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/281.png",
        },
    },
    {
        player: {
            id: 283,
            name: "T. Alexander-Arnold",
            firstname: "Trent",
            lastname: "Alexander-Arnold",
            age: 24,
            birth: {
                date: "1998-10-07",
                place: "Liverpool",
                country: "England",
            },
            nationality: "England",
            height: "175 cm",
            weight: "69 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/283.png",
        },
    },
    {
        player: {
            id: 289,
            name: "A. Robertson",
            firstname: "Andrew",
            lastname: "Robertson",
            age: 28,
            birth: {
                date: "1994-03-11",
                place: "Glasgow",
                country: "Scotland",
            },
            nationality: "Scotland",
            height: "178 cm",
            weight: "64 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/289.png",
        },
    },
    {
        player: {
            id: 290,
            name: "Virgil van Dijk",
            firstname: "Virgil",
            lastname: "van Dijk",
            age: 31,
            birth: {
                date: "1991-07-08",
                place: "Breda",
                country: "Netherlands",
            },
            nationality: "Netherlands",
            height: "193 cm",
            weight: "92 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/290.png",
        },
    },
    {
        player: {
            id: 294,
            name: "N. Keïta",
            firstname: "Naby Laye",
            lastname: "Keïta",
            age: 27,
            birth: {
                date: "1995-02-10",
                place: "Conakry",
                country: "Guinea",
            },
            nationality: "Guinea",
            height: "172 cm",
            weight: "64 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/294.png",
        },
    },
    {
        player: {
            id: 300,
            name: "G. Wijnaldum",
            firstname: "Georginio Gregion Emile",
            lastname: "Wijnaldum",
            age: 32,
            birth: {
                date: "1990-11-11",
                place: "Rotterdam",
                country: "Netherlands",
            },
            nationality: "Netherlands",
            height: "175 cm",
            weight: "69 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/300.png",
        },
    },
    {
        player: {
            id: 304,
            name: "Sadio Mané",
            firstname: "Sadio",
            lastname: "Mané",
            age: 30,
            birth: {
                date: "1992-04-10",
                place: "Sedhiou",
                country: "Senegal",
            },
            nationality: "Senegal",
            height: "175 cm",
            weight: "69 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/304.png",
        },
    },
    {
        player: {
            id: 307,
            name: "Xherdan Shaqiri",
            firstname: "Xherdan",
            lastname: "Shaqiri",
            age: 31,
            birth: {
                date: "1991-10-10",
                place: "Gjilan",
                country: "Kosovo",
            },
            nationality: "Switzerland",
            height: "169 cm",
            weight: "72 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/307.png",
        },
    },
    {
        player: {
            id: 1145,
            name: "I. Konaté",
            firstname: "Ibrahima",
            lastname: "Konaté",
            age: 23,
            birth: {
                date: "1999-05-25",
                place: "Paris",
                country: "France",
            },
            nationality: "France",
            height: "192 cm",
            weight: "93 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/1145.png",
        },
    },
    {
        player: {
            id: 1600,
            name: "K. Tsimikas",
            firstname: "Konstantinos",
            lastname: "Tsimikas",
            age: 26,
            birth: {
                date: "1996-05-12",
                place: "Thessaloníki",
                country: "Greece",
            },
            nationality: "Greece",
            height: "177 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/1600.png",
        },
    },
    {
        player: {
            id: 2678,
            name: "Diogo Jota",
            firstname: "Diogo José",
            lastname: "Teixeira da Silva",
            age: 26,
            birth: {
                date: "1996-12-04",
                place: "Massarelos",
                country: "Portugal",
            },
            nationality: "Portugal",
            height: "178 cm",
            weight: "68 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/2678.png",
        },
    },
    {
        player: {
            id: 19221,
            name: "H. Wilson",
            firstname: "Harry",
            lastname: "Wilson",
            age: 25,
            birth: {
                date: "1997-03-22",
                place: "Wrexham",
                country: "Wales",
            },
            nationality: "Wales",
            height: "173 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/19221.png",
        },
    },
    {
        player: {
            id: 22010,
            name: "S. Ojo",
            firstname: "Oluwaseyi Babajide",
            lastname: "Ojo",
            age: 25,
            birth: {
                date: "1997-06-19",
                place: "Hemel Hempstead",
                country: "England",
            },
            nationality: "England",
            height: "177 cm",
            weight: "64 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/22010.png",
        },
    },
    {
        player: {
            id: 25350,
            name: "M. Grujić",
            firstname: "Marko",
            lastname: "Grujić",
            age: 26,
            birth: {
                date: "1996-04-13",
                place: "Belgrade",
                country: "Serbia",
            },
            nationality: "Serbia",
            height: "191 cm",
            weight: "82 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/25350.png",
        },
    },
    {
        player: {
            id: 26300,
            name: "O. Kabak",
            firstname: "Ozan Muhammed",
            lastname: "Kabak",
            age: 22,
            birth: {
                date: "2000-03-25",
                place: "Ankara",
                country: "Turkey",
            },
            nationality: "Turkey",
            height: "186 cm",
            weight: "86 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/26300.png",
        },
    },
    {
        player: {
            id: 36922,
            name: "S. van den Berg",
            firstname: "Sepp",
            lastname: "van den Berg",
            age: 21,
            birth: {
                date: "2001-12-20",
                place: null,
                country: "Netherlands",
            },
            nationality: "Netherlands",
            height: "189 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/36922.png",
        },
    },
    {
        player: {
            id: 127472,
            name: "N. Phillips",
            firstname: "Nathaniel",
            lastname: "Phillips",
            age: 25,
            birth: {
                date: "1997-03-21",
                place: "Bolton",
                country: "England",
            },
            nationality: "England",
            height: "190 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/127472.png",
        },
    },
    {
        player: {
            id: 138411,
            name: "Liam John Hughes",
            firstname: "Liam John",
            lastname: "Hughes",
            age: 21,
            birth: {
                date: "2001-08-19",
                place: null,
                country: "Northern Ireland",
            },
            nationality: "Northern Ireland",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/138411.png",
        },
    },
    {
        player: {
            id: 138780,
            name: "N. Williams",
            firstname: "Neco Shay",
            lastname: "Williams",
            age: 21,
            birth: {
                date: "2001-04-13",
                place: null,
                country: "Wales",
            },
            nationality: "Wales",
            height: "183 cm",
            weight: "72 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/138780.png",
        },
    },
    {
        player: {
            id: 162687,
            name: "Vítězslav Jaroš",
            firstname: "Vítězslav",
            lastname: "Jaroš",
            age: 21,
            birth: {
                date: "2001-07-23",
                place: null,
                country: "Czech Republic",
            },
            nationality: "Czech Republic",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/162687.png",
        },
    },
    {
        player: {
            id: 180317,
            name: "C. Bradley",
            firstname: "Conor",
            lastname: "Bradley",
            age: 19,
            birth: {
                date: "2003-07-09",
                place: "Dungannon",
                country: "Northern Ireland",
            },
            nationality: "Northern Ireland",
            height: "180 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/180317.png",
        },
    },
];

const mancityAthletes = [
    {
        player: {
            id: 567,
            name: "Rúben Dias",
            firstname: "Rúben",
            lastname: "dos Santos Gato Alves Dias",
            age: 25,
            birth: {
                date: "1997-05-14",
                place: "Amadora",
                country: "Portugal",
            },
            nationality: "Portugal",
            height: "186 cm",
            weight: "76 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/567.png",
        },
    },
    {
        player: {
            id: 617,
            name: "Ederson Santana de Moraes",
            firstname: "Ederson",
            lastname: "Santana de Moraes",
            age: 29,
            birth: {
                date: "1993-08-17",
                place: "Osasco",
                country: "Brazil",
            },
            nationality: "Brazil",
            height: "188 cm",
            weight: "86 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/617.png",
        },
    },
    {
        player: {
            id: 622,
            name: "Aymeric Laporte",
            firstname: "Aymeric",
            lastname: "Laporte",
            age: 28,
            birth: {
                date: "1994-05-27",
                place: "Agen",
                country: "France",
            },
            nationality: "Spain",
            height: "191 cm",
            weight: "86 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/622.png",
        },
    },
    {
        player: {
            id: 623,
            name: "B. Mendy",
            firstname: "Benjamin",
            lastname: "Mendy",
            age: 28,
            birth: {
                date: "1994-07-17",
                place: "Longjumeau",
                country: "France",
            },
            nationality: "France",
            height: "185 cm",
            weight: "85 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/623.png",
        },
    },
    {
        player: {
            id: 625,
            name: "P. Sandler",
            firstname: "Philippe",
            lastname: "Sandler",
            age: 25,
            birth: {
                date: "1997-02-10",
                place: "Amsterdam",
                country: "Netherlands",
            },
            nationality: "Netherlands",
            height: "188 cm",
            weight: "76 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/625.png",
        },
    },
    {
        player: {
            id: 640,
            name: "Fernando Luiz Rosa",
            firstname: "Fernando Luiz",
            lastname: "Rosa",
            age: 37,
            birth: {
                date: "1985-05-04",
                place: "Londrina",
                country: "Brazil",
            },
            nationality: "Brazil",
            height: "179 cm",
            weight: "67 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/640.png",
        },
    },
    {
        player: {
            id: 19128,
            name: "J. Harrison",
            firstname: "Jack",
            lastname: "Harrison",
            age: 26,
            birth: {
                date: "1996-11-20",
                place: "Stoke-on-Trent",
                country: "England",
            },
            nationality: "England",
            height: "175 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/19128.png",
        },
    },
    {
        player: {
            id: 19197,
            name: "Scott Carson",
            firstname: "Scott",
            lastname: "Carson",
            age: 37,
            birth: {
                date: "1985-09-03",
                place: "Whitehaven",
                country: "England",
            },
            nationality: "England",
            height: "183 cm",
            weight: "85 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/19197.png",
        },
    },
    {
        player: {
            id: 50828,
            name: "Zack Steffen",
            firstname: "Zack",
            lastname: "Steffen",
            age: 27,
            birth: {
                date: "1995-04-02",
                place: "Coatesville",
                country: "USA",
            },
            nationality: "USA",
            height: "191 cm",
            weight: "86 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/50828.png",
        },
    },
    {
        player: {
            id: 144731,
            name: "Iker Pozo La Rosa",
            firstname: "Iker",
            lastname: "Pozo La Rosa",
            age: 22,
            birth: {
                date: "2000-08-06",
                place: "Fuengirola",
                country: "Spain",
            },
            nationality: "Spain",
            height: "173 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/144731.png",
        },
    },
    {
        player: {
            id: 152982,
            name: "C. Palmer",
            firstname: "Cole",
            lastname: "Palmer",
            age: 20,
            birth: {
                date: "2002-05-06",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/152982.png",
        },
    },
    {
        player: {
            id: 158696,
            name: "F. Burns",
            firstname: "Finley Jack",
            lastname: "Burns",
            age: 19,
            birth: {
                date: "2003-06-17",
                place: "London",
                country: "England",
            },
            nationality: "England",
            height: "185 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/158696.png",
        },
    },
    {
        player: {
            id: 158697,
            name: "J. McAtee",
            firstname: "James John",
            lastname: "McAtee",
            age: 20,
            birth: {
                date: "2002-10-18",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/158697.png",
        },
    },
    {
        player: {
            id: 158702,
            name: "C. Slicker",
            firstname: "Cieran",
            lastname: "Slicker",
            age: 20,
            birth: {
                date: "2002-09-15",
                place: "Oldham",
                country: "England",
            },
            nationality: "Scotland",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/158702.png",
        },
    },
    {
        player: {
            id: 181827,
            name: "C. Egan-Riley",
            firstname: "Conrad Jonathan",
            lastname: "Egan-Riley",
            age: 19,
            birth: {
                date: "2003-01-02",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/181827.png",
        },
    },
    {
        player: {
            id: 278128,
            name: "J. Wilson-Esbrand",
            firstname: "Joshua Darius",
            lastname: "Kamani Wilson-Esbrand",
            age: 20,
            birth: {
                date: "2002-12-26",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/278128.png",
        },
    },
    {
        player: {
            id: 278129,
            name: "L. Mbete-Tabu",
            firstname: "Luke",
            lastname: "Mbete-Tabu",
            age: 19,
            birth: {
                date: "2003-09-18",
                place: null,
                country: "Ghana",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/278129.png",
        },
    },
    {
        player: {
            id: 282125,
            name: "R. Lavia",
            firstname: "Roméo",
            lastname: "Lavia",
            age: 18,
            birth: {
                date: "2004-01-06",
                place: null,
                country: "Belgium",
            },
            nationality: "Belgium",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/282125.png",
        },
    },
    {
        player: {
            id: 284231,
            name: "Micah Hamilton",
            firstname: "Micah",
            lastname: "Hamilton",
            age: 19,
            birth: {
                date: "2003-11-13",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/284231.png",
        },
    },
    {
        player: {
            id: 284355,
            name: "Mikki Avelon Leander van Sas",
            firstname: "Mikki Avelon Leander",
            lastname: "van Sas",
            age: 18,
            birth: {
                date: "2004-02-29",
                place: null,
                country: "Netherlands",
            },
            nationality: "Netherlands",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/284355.png",
        },
    },
    {
        player: {
            id: 44,
            name: "Rodri",
            firstname: "Rodrigo",
            lastname: "Hernández Cascante",
            age: 26,
            birth: {
                date: "1996-06-22",
                place: "Madrid",
                country: "Spain",
            },
            nationality: "Spain",
            height: "191 cm",
            weight: "82 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/44.png",
        },
    },
    {
        player: {
            id: 615,
            name: "Daniel James Grimshaw",
            firstname: "Daniel James",
            lastname: "Grimshaw",
            age: 24,
            birth: {
                date: "1998-01-16",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: "185 cm",
            weight: "77 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/615.png",
        },
    },
    {
        player: {
            id: 626,
            name: "John Stones",
            firstname: "John",
            lastname: "Stones",
            age: 28,
            birth: {
                date: "1994-05-28",
                place: "Barnsley",
                country: "England",
            },
            nationality: "England",
            height: "188 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/626.png",
        },
    },
    {
        player: {
            id: 632,
            name: "C. Gomes",
            firstname: "Claudio",
            lastname: "Gomes",
            age: 22,
            birth: {
                date: "2000-07-23",
                place: "Argenteuil",
                country: "France",
            },
            nationality: "France",
            height: "180 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/632.png",
        },
    },
    {
        player: {
            id: 633,
            name: "İlkay Gündoğan",
            firstname: "İlkay",
            lastname: "Gündoğan",
            age: 32,
            birth: {
                date: "1990-10-24",
                place: "Gelsenkirchen",
                country: "Germany",
            },
            nationality: "Germany",
            height: "180 cm",
            weight: "80 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/633.png",
        },
    },
    {
        player: {
            id: 635,
            name: "Riyad Mahrez",
            firstname: "Riyad",
            lastname: "Mahrez",
            age: 31,
            birth: {
                date: "1991-02-21",
                place: "Sarcelles",
                country: "France",
            },
            nationality: "Algeria",
            height: "179 cm",
            weight: "67 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/635.png",
        },
    },
    {
        player: {
            id: 636,
            name: "Bernardo Silva",
            firstname: "Bernardo",
            lastname: "Mota Veiga de Carvalho e Silva",
            age: 28,
            birth: {
                date: "1994-08-10",
                place: "Lisboa",
                country: "Portugal",
            },
            nationality: "Portugal",
            height: "173 cm",
            weight: "64 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/636.png",
        },
    },
    {
        player: {
            id: 643,
            name: "Gabriel Jesus",
            firstname: "Gabriel Fernando",
            lastname: "de Jesus",
            age: 25,
            birth: {
                date: "1997-04-03",
                place: "São Paulo",
                country: "Brazil",
            },
            nationality: "Brazil",
            height: "175 cm",
            weight: "73 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/643.png",
        },
    },
    {
        player: {
            id: 855,
            name: "João Pedro Cavaco Cancelo",
            firstname: "João Pedro",
            lastname: "Cavaco Cancelo",
            age: 28,
            birth: {
                date: "1994-05-27",
                place: "Barreiro",
                country: "Portugal",
            },
            nationality: "Portugal",
            height: "182 cm",
            weight: "74 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/855.png",
        },
    },
    {
        player: {
            id: 19170,
            name: "M. Rogers",
            firstname: "Morgan Elliot",
            lastname: "Rogers",
            age: 20,
            birth: {
                date: "2002-07-26",
                place: "Halesowen",
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/19170.png",
        },
    },
    {
        player: {
            id: 20277,
            name: "Luke Phillip Bolton",
            firstname: "Luke Phillip",
            lastname: "Bolton",
            age: 23,
            birth: {
                date: "1999-10-07",
                place: "Stockport",
                country: "England",
            },
            nationality: "England",
            height: "176 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/20277.png",
        },
    },
    {
        player: {
            id: 47521,
            name: "Patrick John Joseph Roberts",
            firstname: "Patrick John Joseph",
            lastname: "Roberts",
            age: 25,
            birth: {
                date: "1997-02-05",
                place: "Kingston upon Thames",
                country: "England",
            },
            nationality: "England",
            height: "168 cm",
            weight: "58 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/47521.png",
        },
    },
    {
        player: {
            id: 144730,
            name: "Alpha Richard Diounkou Tecagne",
            firstname: "Alpha Richard",
            lastname: "Diounkou Tecagne",
            age: 21,
            birth: {
                date: "2001-10-10",
                place: "Sindone",
                country: "Senegal",
            },
            nationality: "Senegal",
            height: "183 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/144730.png",
        },
    },
    {
        player: {
            id: 144732,
            name: "T. Doyle",
            firstname: "Thomas Glyn",
            lastname: "Doyle",
            age: 21,
            birth: {
                date: "2001-10-17",
                place: "Manchester",
                country: "England",
            },
            nationality: "England",
            height: "172 cm",
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/144732.png",
        },
    },
    {
        player: {
            id: 144733,
            name: "B. Knight",
            firstname: "Benjamin Leo",
            lastname: "Knight",
            age: 20,
            birth: {
                date: "2002-06-14",
                place: "Cambridge",
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/144733.png",
        },
    },
    {
        player: {
            id: 161948,
            name: "L. Delap",
            firstname: "Liam Rory",
            lastname: "Delap",
            age: 19,
            birth: {
                date: "2003-02-08",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/161948.png",
        },
    },
    {
        player: {
            id: 197448,
            name: "Yan Couto",
            firstname: "Yan",
            lastname: "Bueno Couto",
            age: 20,
            birth: {
                date: "2002-06-03",
                place: "Curitiba",
                country: "Brazil",
            },
            nationality: "Brazil",
            height: "168 cm",
            weight: "60 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/197448.png",
        },
    },
    {
        player: {
            id: 278085,
            name: "S. Edozie",
            firstname: "Samuel",
            lastname: "Edozie",
            age: 19,
            birth: {
                date: "2003-01-28",
                place: null,
                country: "England",
            },
            nationality: "England",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/278085.png",
        },
    },
    {
        player: {
            id: 278133,
            name: "O. Bobb",
            firstname: "Oscar",
            lastname: "Bobb",
            age: 19,
            birth: {
                date: "2003-07-12",
                place: null,
                country: "Norway",
            },
            nationality: "Norway",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/278133.png",
        },
    },
    {
        player: {
            id: 305819,
            name: "Kayky",
            firstname: "Kayky",
            lastname: "da Silva Chagas",
            age: 19,
            birth: {
                date: "2003-06-11",
                place: null,
                country: "Brazil",
            },
            nationality: "Brazil",
            height: "170 cm",
            weight: "67 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/305819.png",
        },
    },
    {
        player: {
            id: 627,
            name: "Kyle Walker",
            firstname: "Kyle",
            lastname: "Walker",
            age: 32,
            birth: {
                date: "1990-05-28",
                place: "Sheffield",
                country: "England",
            },
            nationality: "England",
            height: "178 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/627.png",
        },
    },
    {
        player: {
            id: 629,
            name: "Kevin De Bruyne",
            firstname: "Kevin",
            lastname: "De Bruyne",
            age: 31,
            birth: {
                date: "1991-06-28",
                place: "Drongen",
                country: "Belgium",
            },
            nationality: "Belgium",
            height: "181 cm",
            weight: "68 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/629.png",
        },
    },
    {
        player: {
            id: 631,
            name: "P. Foden",
            firstname: "Philip",
            lastname: "Foden",
            age: 22,
            birth: {
                date: "2000-05-28",
                place: "Stockport",
                country: "England",
            },
            nationality: "England",
            height: "171 cm",
            weight: "70 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/631.png",
        },
    },
    {
        player: {
            id: 641,
            name: "O. Zinchenko",
            firstname: "Oleksandr",
            lastname: "Zinchenko",
            age: 26,
            birth: {
                date: "1996-12-15",
                place: "Radomyshl",
                country: "Ukraine",
            },
            nationality: "Ukraine",
            height: "175 cm",
            weight: "64 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/641.png",
        },
    },
    {
        player: {
            id: 645,
            name: "Raheem Sterling",
            firstname: "Raheem",
            lastname: "Sterling",
            age: 28,
            birth: {
                date: "1994-12-08",
                place: "Kingston",
                country: "Jamaica",
            },
            nationality: "England",
            height: "170 cm",
            weight: "69 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/645.png",
        },
    },
    {
        player: {
            id: 880,
            name: "Pablo Moreno",
            firstname: "Pablo",
            lastname: "Moreno Taboada",
            age: 20,
            birth: {
                date: "2002-05-03",
                place: "Granada",
                country: "Spain",
            },
            nationality: "Spain",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/880.png",
        },
    },
    {
        player: {
            id: 931,
            name: "Ferran Torres",
            firstname: "Ferran",
            lastname: "Torres García",
            age: 22,
            birth: {
                date: "2000-02-29",
                place: "Foios",
                country: "Spain",
            },
            nationality: "Spain",
            height: "184 cm",
            weight: "77 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/931.png",
        },
    },
    {
        player: {
            id: 18861,
            name: "Nathan Benjamin Aké",
            firstname: "Nathan Benjamin",
            lastname: "Aké",
            age: 27,
            birth: {
                date: "1995-02-18",
                place: "Den Haag",
                country: "Netherlands",
            },
            nationality: "Netherlands",
            height: "180 cm",
            weight: "75 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/18861.png",
        },
    },
    {
        player: {
            id: 19187,
            name: "J. Grealish",
            firstname: "Jack",
            lastname: "Grealish",
            age: 27,
            birth: {
                date: "1995-09-10",
                place: "Birmingham",
                country: "England",
            },
            nationality: "England",
            height: "175 cm",
            weight: "68 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/19187.png",
        },
    },
    {
        player: {
            id: 36843,
            name: "Matthew Robert Smith",
            firstname: "Matthew Robert",
            lastname: "Smith",
            age: 23,
            birth: {
                date: "1999-11-22",
                place: "Redditch",
                country: "England",
            },
            nationality: "Wales",
            height: "175 cm",
            weight: "71 kg",
            injured: false,
            photo: "https://media.api-sports.io/football/players/36843.png",
        },
    },
    {
        player: {
            id: 284356,
            name: "Shea Charles",
            firstname: "Shea",
            lastname: "Charles",
            age: 19,
            birth: {
                date: "2003-11-05",
                place: null,
                country: "England",
            },
            nationality: "Northern Ireland",
            height: null,
            weight: null,
            injured: false,
            photo: "https://media.api-sports.io/football/players/284356.png",
        },
    },
];

const apiFootballAthleteToHuddleMap = (a: any) => ({
    name: a.player.name,
    firstname: a.player.firstname,
    lastname: a.player.lastname,
    nationality: a.player.nationality,
    photo: a.player.photo,
    sources: { apiFootball: { id: a.player.id } },
});

export const athleteSeed = [
    ...livAthletes.map(apiFootballAthleteToHuddleMap),
    ...mancityAthletes.map(apiFootballAthleteToHuddleMap),
];

export const teamAthleteSeed = [
    ...Array.from({ length: livAthletes.length }, (_, i) => ({
        athleteId: i + 1,
        teamId: 5,
    })),
    ...Array.from({ length: mancityAthletes.length }, (_, i) => ({
        athleteId: i + livAthletes.length + 1,
        teamId: 14,
    })),
];
