import { Sport } from "@prisma/client";
import { config } from "../../../../../lib/config";

const eplRaw = [
    {
        team: {
            id: 33,
            name: "Manchester United",
            code: "MUN",
            country: "England",
            founded: 1878,
            national: false,
            logo: "https://media.api-sports.io/football/teams/33.png",
        },
        venue: {
            id: 556,
            name: "Old Trafford",
            address: "Sir Matt Busby Way",
            city: "Manchester",
            capacity: 76212,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/556.png",
        },
    },
    {
        team: {
            id: 34,
            name: "Newcastle",
            code: "NEW",
            country: "England",
            founded: 1892,
            national: false,
            logo: "https://media.api-sports.io/football/teams/34.png",
        },
        venue: {
            id: 562,
            name: "St. James' Park",
            address: "St. James&apos; Street",
            city: "Newcastle upon Tyne",
            capacity: 52389,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/562.png",
        },
    },
    {
        team: {
            id: 35,
            name: "Bournemouth",
            code: "BOU",
            country: "England",
            founded: 1899,
            national: false,
            logo: "https://media.api-sports.io/football/teams/35.png",
        },
        venue: {
            id: 504,
            name: "Vitality Stadium",
            address: "Dean Court, Kings Park",
            city: "Bournemouth, Dorset",
            capacity: 12000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/504.png",
        },
    },
    {
        team: {
            id: 36,
            name: "Fulham",
            code: "FUL",
            country: "England",
            founded: 1879,
            national: false,
            logo: "https://media.api-sports.io/football/teams/36.png",
        },
        venue: {
            id: 535,
            name: "Craven Cottage",
            address: "Stevenage Road",
            city: "London",
            capacity: 25700,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/535.png",
        },
    },
    {
        team: {
            id: 39,
            name: "Wolves",
            code: "WOL",
            country: "England",
            founded: 1877,
            national: false,
            logo: "https://media.api-sports.io/football/teams/39.png",
        },
        venue: {
            id: 600,
            name: "Molineux Stadium",
            address: "Waterloo Road",
            city: "Wolverhampton, West Midlands",
            capacity: 32050,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/600.png",
        },
    },
    {
        team: {
            id: 40,
            name: "Liverpool",
            code: "LIV",
            country: "England",
            founded: 1892,
            national: false,
            logo: "https://media.api-sports.io/football/teams/40.png",
        },
        venue: {
            id: 550,
            name: "Anfield",
            address: "Anfield Road",
            city: "Liverpool",
            capacity: 55212,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/550.png",
        },
    },
    {
        team: {
            id: 41,
            name: "Southampton",
            code: "SOU",
            country: "England",
            founded: 1885,
            national: false,
            logo: "https://media.api-sports.io/football/teams/41.png",
        },
        venue: {
            id: 585,
            name: "St. Mary's Stadium",
            address: "Britannia Road",
            city: "Southampton, Hampshire",
            capacity: 32689,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/585.png",
        },
    },
    {
        team: {
            id: 42,
            name: "Arsenal",
            code: "ARS",
            country: "England",
            founded: 1886,
            national: false,
            logo: "https://media.api-sports.io/football/teams/42.png",
        },
        venue: {
            id: 494,
            name: "Emirates Stadium",
            address: "Queensland Road",
            city: "London",
            capacity: 60383,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/494.png",
        },
    },
    {
        team: {
            id: 45,
            name: "Everton",
            code: "EVE",
            country: "England",
            founded: 1878,
            national: false,
            logo: "https://media.api-sports.io/football/teams/45.png",
        },
        venue: {
            id: 8560,
            name: "Goodison Park",
            address: "Goodison Road",
            city: "Liverpool",
            capacity: 40569,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/8560.png",
        },
    },
    {
        team: {
            id: 46,
            name: "Leicester",
            code: "LEI",
            country: "England",
            founded: 1884,
            national: false,
            logo: "https://media.api-sports.io/football/teams/46.png",
        },
        venue: {
            id: 547,
            name: "King Power Stadium",
            address: "Filbert Way",
            city: "Leicester, Leicestershire",
            capacity: 34310,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/547.png",
        },
    },
    {
        team: {
            id: 47,
            name: "Tottenham",
            code: "TOT",
            country: "England",
            founded: 1882,
            national: false,
            logo: "https://media.api-sports.io/football/teams/47.png",
        },
        venue: {
            id: 593,
            name: "Tottenham Hotspur Stadium",
            address: "Bill Nicholson Way, 748 High Road",
            city: "London",
            capacity: 62062,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/593.png",
        },
    },
    {
        team: {
            id: 48,
            name: "West Ham",
            code: "WES",
            country: "England",
            founded: 1895,
            national: false,
            logo: "https://media.api-sports.io/football/teams/48.png",
        },
        venue: {
            id: 598,
            name: "London Stadium",
            address: "Marshgate Lane, Stratford",
            city: "London",
            capacity: 60000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/598.png",
        },
    },
    {
        team: {
            id: 49,
            name: "Chelsea",
            code: "CHE",
            country: "England",
            founded: 1905,
            national: false,
            logo: "https://media.api-sports.io/football/teams/49.png",
        },
        venue: {
            id: 519,
            name: "Stamford Bridge",
            address: "Fulham Road",
            city: "London",
            capacity: 41841,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/519.png",
        },
    },
    {
        team: {
            id: 50,
            name: "Manchester City",
            code: "MAC",
            country: "England",
            founded: 1880,
            national: false,
            logo: "https://media.api-sports.io/football/teams/50.png",
        },
        venue: {
            id: 555,
            name: "Etihad Stadium",
            address: "Rowsley Street",
            city: "Manchester",
            capacity: 55097,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/555.png",
        },
    },
    {
        team: {
            id: 51,
            name: "Brighton",
            code: "BRI",
            country: "England",
            founded: 1901,
            national: false,
            logo: "https://media.api-sports.io/football/teams/51.png",
        },
        venue: {
            id: 508,
            name: "The American Express Community Stadium",
            address: "Village Way",
            city: "Falmer, East Sussex",
            capacity: 31800,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/508.png",
        },
    },
    {
        team: {
            id: 52,
            name: "Crystal Palace",
            code: "CRY",
            country: "England",
            founded: 1905,
            national: false,
            logo: "https://media.api-sports.io/football/teams/52.png",
        },
        venue: {
            id: 525,
            name: "Selhurst Park",
            address: "Holmesdale Road",
            city: "London",
            capacity: 26309,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/525.png",
        },
    },
    {
        team: {
            id: 55,
            name: "Brentford",
            code: "BRE",
            country: "England",
            founded: 1889,
            national: false,
            logo: "https://media.api-sports.io/football/teams/55.png",
        },
        venue: {
            id: 10503,
            name: "Brentford Community Stadium",
            address: "166 Lionel Rd N, Brentford",
            city: "Brentford, Middlesex",
            capacity: 17250,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/10503.png",
        },
    },
    {
        team: {
            id: 63,
            name: "Leeds",
            code: "LEE",
            country: "England",
            founded: 1919,
            national: false,
            logo: "https://media.api-sports.io/football/teams/63.png",
        },
        venue: {
            id: 546,
            name: "Elland Road",
            address: "Elland Road",
            city: "Leeds, West Yorkshire",
            capacity: 40204,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/546.png",
        },
    },
    {
        team: {
            id: 65,
            name: "Nottingham Forest",
            code: "NOT",
            country: "England",
            founded: 1865,
            national: false,
            logo: "https://media.api-sports.io/football/teams/65.png",
        },
        venue: {
            id: 566,
            name: "The City Ground",
            address: "Pavilion Road",
            city: "Nottingham, Nottinghamshire",
            capacity: 30576,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/566.png",
        },
    },
    {
        team: {
            id: 66,
            name: "Aston Villa",
            code: "AST",
            country: "England",
            founded: 1874,
            national: false,
            logo: "https://media.api-sports.io/football/teams/66.png",
        },
        venue: {
            id: 495,
            name: "Villa Park",
            address: "Trinity Road",
            city: "Birmingham",
            capacity: 42788,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/495.png",
        },
    },
];

const mlsRaw = [
    {
        team: {
            id: 1595,
            name: "Seattle Sounders",
            code: "SEA",
            country: "USA",
            founded: 2007,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1595.png",
        },
        venue: {
            id: 11534,
            name: "Lumen Field",
            address: "800 Occidental Avenue South",
            city: "Seattle, Washington",
            capacity: 72000,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/11534.png",
        },
    },
    {
        team: {
            id: 1596,
            name: "San Jose Earthquakes",
            code: "JOS",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1596.png",
        },
        venue: {
            id: 11918,
            name: "PayPal Park",
            address: "1123 Coleman Avenue",
            city: "San Jose, California",
            capacity: 18000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/11918.png",
        },
    },
    {
        team: {
            id: 1597,
            name: "FC Dallas",
            code: "DAL",
            country: "USA",
            founded: 1996,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1597.png",
        },
        venue: {
            id: 1612,
            name: "Toyota Stadium",
            address: "6000 Main Street",
            city: "Frisco, Texas",
            capacity: 22565,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1612.png",
        },
    },
    {
        team: {
            id: 1598,
            name: "Orlando City SC",
            code: "ORL",
            country: "USA",
            founded: 2008,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1598.png",
        },
        venue: {
            id: 1838,
            name: "Exploria Stadium",
            address: "655 West Church Street",
            city: "Orlando, Florida",
            capacity: 25527,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1838.png",
        },
    },
    {
        team: {
            id: 1599,
            name: "Philadelphia Union",
            code: "PHI",
            country: "USA",
            founded: 2008,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1599.png",
        },
        venue: {
            id: 1620,
            name: "Subaru Park",
            address: "Seaport Drive",
            city: "Chester, Pennsylvania",
            capacity: 19487,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1620.png",
        },
    },
    {
        team: {
            id: 1600,
            name: "Houston Dynamo",
            code: "HOU",
            country: "USA",
            founded: 2005,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1600.png",
        },
        venue: {
            id: 12599,
            name: "PNC Stadium",
            address: "2200 Texas Avenue, East End",
            city: "Houston, Texas",
            capacity: 22661,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/12599.png",
        },
    },
    {
        team: {
            id: 1601,
            name: "Toronto FC",
            code: "TOR",
            country: "Canada",
            founded: 2006,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1601.png",
        },
        venue: {
            id: 312,
            name: "BMO Field",
            address: "170 Princes’ Boulevard",
            city: "Toronto, Ontario",
            capacity: 36045,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/312.png",
        },
    },
    {
        team: {
            id: 1602,
            name: "New York Red Bulls",
            code: "YOR",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1602.png",
        },
        venue: {
            id: 1619,
            name: "Red Bull Arena",
            address: "Frank Rogers Boulevard South",
            city: "Harrison, New Jersey",
            capacity: 26765,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1619.png",
        },
    },
    {
        team: {
            id: 1603,
            name: "Vancouver Whitecaps",
            code: "VAN",
            country: "Canada",
            founded: 1986,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1603.png",
        },
        venue: {
            id: 313,
            name: "BC Place Stadium",
            address: "777 Pacific Boulevard, False Creek",
            city: "Vancouver, British Columbia",
            capacity: 59687,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/313.png",
        },
    },
    {
        team: {
            id: 1604,
            name: "New York City FC",
            code: "NYC",
            country: "USA",
            founded: 2013,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1604.png",
        },
        venue: {
            id: 1833,
            name: "Yankee Stadium",
            address: "One East 161st Street, The Bronx",
            city: "New York City",
            capacity: 54251,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1833.png",
        },
    },
    {
        team: {
            id: 1605,
            name: "Los Angeles Galaxy",
            code: "ANG",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1605.png",
        },
        venue: {
            id: 1616,
            name: "Dignity Health Sports Park",
            address: "18400 Avalon Boulevard, Dominguez Hills",
            city: "Carson, California",
            capacity: 30510,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1616.png",
        },
    },
    {
        team: {
            id: 1606,
            name: "Real Salt Lake",
            code: "SAL",
            country: "USA",
            founded: 2004,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1606.png",
        },
        venue: {
            id: 1621,
            name: "Rio Tinto Stadium",
            address: "9256 South State Street",
            city: "Sandy, Utah",
            capacity: 21363,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1621.png",
        },
    },
    {
        team: {
            id: 1607,
            name: "Chicago Fire",
            code: "CHI",
            country: "USA",
            founded: 1997,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1607.png",
        },
        venue: {
            id: 1609,
            name: "Soldier Field",
            address: "1410 South Museum Campus Drive",
            city: "Chicago, Illinois",
            capacity: 62493,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1609.png",
        },
    },
    {
        team: {
            id: 1608,
            name: "Atlanta United FC",
            code: "ATL",
            country: "USA",
            founded: 2014,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1608.png",
        },
        venue: {
            id: 1898,
            name: "Mercedes-Benz Stadium",
            address: "1 AMB Drive North West",
            city: "Atlanta, Georgia",
            capacity: 73019,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/1898.png",
        },
    },
    {
        team: {
            id: 1609,
            name: "New England Revolution",
            code: "ENG",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1609.png",
        },
        venue: {
            id: 1618,
            name: "Gillette Stadium",
            address: "1388 One Patriot Place",
            city: "Foxborough, Massachusetts",
            capacity: 68756,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/1618.png",
        },
    },
    {
        team: {
            id: 1610,
            name: "Colorado Rapids",
            code: "COL",
            country: "USA",
            founded: 1996,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1610.png",
        },
        venue: {
            id: 1610,
            name: "Dick's Sporting Goods Park",
            address: "6000 Victory Way, Commerce City",
            city: "Denver, Colorado",
            capacity: 19734,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1610.png",
        },
    },
    {
        team: {
            id: 1611,
            name: "Sporting Kansas City",
            code: "KAN",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1611.png",
        },
        venue: {
            id: 1615,
            name: "Children's Mercy Park",
            address: "One Sporting Way",
            city: "Kansas City, Kansas",
            capacity: 21650,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1615.png",
        },
    },
    {
        team: {
            id: 1612,
            name: "Minnesota United FC",
            code: "MIN",
            country: "USA",
            founded: 2010,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1612.png",
        },
        venue: {
            id: 1617,
            name: "Allianz Field",
            address: "400 Snelling Avenue North",
            city: "Saint Paul, Minnesota",
            capacity: 19939,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1617.png",
        },
    },
    {
        team: {
            id: 1613,
            name: "Columbus Crew",
            code: "COL",
            country: "USA",
            founded: 1996,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1613.png",
        },
        venue: {
            id: 12667,
            name: "Lower.com Field",
            address: "560 West Nationwide Boulevard",
            city: "Columbus, Ohio",
            capacity: 20407,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/12667.png",
        },
    },
    {
        team: {
            id: 1614,
            name: "Montreal Impact",
            code: "MON",
            country: "Canada",
            founded: 2010,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1614.png",
        },
        venue: {
            id: 310,
            name: "Stade Saputo",
            address: "4750, rue Sherbrooke Est",
            city: "Montreal, Quebec",
            capacity: 20801,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/310.png",
        },
    },
    {
        team: {
            id: 1615,
            name: "DC United",
            code: "UNI",
            country: "USA",
            founded: 1996,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1615.png",
        },
        venue: {
            id: 1613,
            name: "Audi Field",
            address: "32-60 R Street South West, Buzzard Point",
            city: "Washington, District of Columbia",
            capacity: 20600,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1613.png",
        },
    },
    {
        team: {
            id: 1616,
            name: "Los Angeles FC",
            code: "LAFC",
            country: "USA",
            founded: 2014,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1616.png",
        },
        venue: {
            id: 1922,
            name: "Banc of California Stadium",
            address: "3939 S Figueroa Street",
            city: "Los Angeles, California",
            capacity: 22902,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1922.png",
        },
    },
    {
        team: {
            id: 1617,
            name: "Portland Timbers",
            code: "POR",
            country: "USA",
            founded: 2009,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1617.png",
        },
        venue: {
            id: 1748,
            name: "Providence Park",
            address: "1844 SW Morrison Street",
            city: "Portland, Oregon",
            capacity: 25518,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/1748.png",
        },
    },
    {
        team: {
            id: 2242,
            name: "FC Cincinnati",
            code: "CIN",
            country: "USA",
            founded: null,
            national: false,
            logo: "https://media.api-sports.io/football/teams/2242.png",
        },
        venue: {
            id: 3076,
            name: "Nippert Stadium",
            address: "2700 Bearcats Way",
            city: "Cincinnati, Ohio",
            capacity: 40000,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/3076.png",
        },
    },
    {
        team: {
            id: 9568,
            name: "Inter Miami",
            code: "MIA",
            country: "USA",
            founded: 2018,
            national: false,
            logo: "https://media.api-sports.io/football/teams/9568.png",
        },
        venue: {
            id: 11976,
            name: "DRV PNK Stadium",
            address: "1350 Northwest 55th Street",
            city: "Fort Lauderdale, Florida",
            capacity: 18535,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/11976.png",
        },
    },
    {
        team: {
            id: 9569,
            name: "Nashville SC",
            code: "NSH",
            country: "USA",
            founded: 2020,
            national: false,
            logo: "https://media.api-sports.io/football/teams/9569.png",
        },
        venue: {
            id: 12697,
            name: "Nashville SC Stadium",
            address: "513 Benton Avenue",
            city: "Nashville, Tennessee",
            capacity: 30000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/12697.png",
        },
    },
    {
        team: {
            id: 16489,
            name: "Austin",
            code: "ATX",
            country: "USA",
            founded: 2021,
            national: false,
            logo: "https://media.api-sports.io/football/teams/16489.png",
        },
        venue: {
            id: 11535,
            name: "Q2 Stadium",
            address: "10414 Mc Kalla Place",
            city: "Austin, Texas",
            capacity: 20738,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/11535.png",
        },
    },
    {
        team: {
            id: 18310,
            name: "Charlotte",
            code: "CLT",
            country: "USA",
            founded: null,
            national: false,
            logo: "https://media.api-sports.io/football/teams/18310.png",
        },
        venue: {
            id: null,
            name: null,
            address: null,
            city: null,
            capacity: null,
            surface: null,
            image: null,
        },
    },
];

const laLigaRaw = [
    {
        team: {
            id: 529,
            name: "Barcelona",
            code: "BAR",
            country: "Spain",
            founded: 1899,
            national: false,
            logo: "https://media.api-sports.io/football/teams/529.png",
        },
        venue: {
            id: 18630,
            name: "Spotify Camp Nou",
            address: "Carrer d&apos;Arístides Maillol",
            city: "Barcelona",
            capacity: 99787,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/18630.png",
        },
    },
    {
        team: {
            id: 530,
            name: "Atletico Madrid",
            code: "MAD",
            country: "Spain",
            founded: 1903,
            national: false,
            logo: "https://media.api-sports.io/football/teams/530.png",
        },
        venue: {
            id: 1461,
            name: "Estadio Wanda Metropolitano",
            address: "Rosas",
            city: "Madrid",
            capacity: 68032,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1461.png",
        },
    },
    {
        team: {
            id: 531,
            name: "Athletic Club",
            code: "BIL",
            country: "Spain",
            founded: 1898,
            national: false,
            logo: "https://media.api-sports.io/football/teams/531.png",
        },
        venue: {
            id: 1460,
            name: "San Mamés Barria",
            address: "Rafael Moreno Pitxitxi Kalea",
            city: "Bilbao",
            capacity: 53289,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1460.png",
        },
    },
    {
        team: {
            id: 532,
            name: "Valencia",
            code: "VAL",
            country: "Spain",
            founded: 1919,
            national: false,
            logo: "https://media.api-sports.io/football/teams/532.png",
        },
        venue: {
            id: 1497,
            name: "Estadio de Mestalla",
            address: "Avenida de Suecia",
            city: "Valencia",
            capacity: 55000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1497.png",
        },
    },
    {
        team: {
            id: 533,
            name: "Villarreal",
            code: "VIL",
            country: "Spain",
            founded: 1923,
            national: false,
            logo: "https://media.api-sports.io/football/teams/533.png",
        },
        venue: {
            id: 1498,
            name: "Estadio de la Cerámica",
            address: "Plaza Labrador",
            city: "Villarreal",
            capacity: 24500,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1498.png",
        },
    },
    {
        team: {
            id: 536,
            name: "Sevilla",
            code: "SEV",
            country: "Spain",
            founded: 1890,
            national: false,
            logo: "https://media.api-sports.io/football/teams/536.png",
        },
        venue: {
            id: 1494,
            name: "Estadio Ramón Sánchez Pizjuán",
            address: "Avenida de Eduardo Dato",
            city: "Sevilla",
            capacity: 48649,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1494.png",
        },
    },
    {
        team: {
            id: 538,
            name: "Celta Vigo",
            code: "CEL",
            country: "Spain",
            founded: 1923,
            national: false,
            logo: "https://media.api-sports.io/football/teams/538.png",
        },
        venue: {
            id: 1467,
            name: "Abanca-Balaídos",
            address: "Avenida de Balaídos",
            city: "Vigo",
            capacity: 31800,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1467.png",
        },
    },
    {
        team: {
            id: 540,
            name: "Espanyol",
            code: "ESP",
            country: "Spain",
            founded: 1900,
            national: false,
            logo: "https://media.api-sports.io/football/teams/540.png",
        },
        venue: {
            id: 1474,
            name: "RCDE Stadium",
            address: "Avenida Baix Llobregat 100",
            city: "Cornella de Llobregat",
            capacity: 40423,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1474.png",
        },
    },
    {
        team: {
            id: 541,
            name: "Real Madrid",
            code: "REA",
            country: "Spain",
            founded: 1902,
            national: false,
            logo: "https://media.api-sports.io/football/teams/541.png",
        },
        venue: {
            id: 1456,
            name: "Estadio Santiago Bernabéu",
            address: "Avenida de Concha Espina 1, Chamartín",
            city: "Madrid",
            capacity: 85454,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1456.png",
        },
    },
    {
        team: {
            id: 543,
            name: "Real Betis",
            code: "BET",
            country: "Spain",
            founded: 1907,
            national: false,
            logo: "https://media.api-sports.io/football/teams/543.png",
        },
        venue: {
            id: 1489,
            name: "Estadio Benito Villamarín",
            address: "Avenida de Heliópolis",
            city: "Sevilla",
            capacity: 60721,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1489.png",
        },
    },
    {
        team: {
            id: 546,
            name: "Getafe",
            code: "GET",
            country: "Spain",
            founded: 1983,
            national: false,
            logo: "https://media.api-sports.io/football/teams/546.png",
        },
        venue: {
            id: 1476,
            name: "Coliseum Alfonso Pérez",
            address: "Avenida de Teresa de Calcuta",
            city: "Getafe",
            capacity: 17393,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1476.png",
        },
    },
    {
        team: {
            id: 547,
            name: "Girona",
            code: "GIR",
            country: "Spain",
            founded: 1930,
            national: false,
            logo: "https://media.api-sports.io/football/teams/547.png",
        },
        venue: {
            id: 1478,
            name: "Estadi Municipal de Montilivi",
            address: "Avenida Montlivi 141",
            city: "Girona",
            capacity: 14500,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1478.png",
        },
    },
    {
        team: {
            id: 548,
            name: "Real Sociedad",
            code: "RSO",
            country: "Spain",
            founded: 1909,
            national: false,
            logo: "https://media.api-sports.io/football/teams/548.png",
        },
        venue: {
            id: 1491,
            name: "Reale Arena",
            address: "Paseo de Anoeta 1",
            city: "Donostia-San Sebastián",
            capacity: 39500,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1491.png",
        },
    },
    {
        team: {
            id: 720,
            name: "Valladolid",
            code: "VAL",
            country: "Spain",
            founded: 1928,
            national: false,
            logo: "https://media.api-sports.io/football/teams/720.png",
        },
        venue: {
            id: 1492,
            name: "Estadio Municipal José Zorrilla",
            address: "Avenida del Mundial 82",
            city: "Valladolid",
            capacity: 26512,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1492.png",
        },
    },
    {
        team: {
            id: 723,
            name: "Almeria",
            code: "ALM",
            country: "Spain",
            founded: 1989,
            national: false,
            logo: "https://media.api-sports.io/football/teams/723.png",
        },
        venue: {
            id: 1459,
            name: "Estadio de los Juegos Mediterráneos",
            address: "Calle de Belladona",
            city: "Almería",
            capacity: 21350,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1459.png",
        },
    },
    {
        team: {
            id: 724,
            name: "Cadiz",
            code: "CAD",
            country: "Spain",
            founded: 1910,
            national: false,
            logo: "https://media.api-sports.io/football/teams/724.png",
        },
        venue: {
            id: 11915,
            name: "Estadio Nuevo Mirandilla",
            address: "Plaza de Madrid",
            city: "Cádiz",
            capacity: 22000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/11915.png",
        },
    },
    {
        team: {
            id: 727,
            name: "Osasuna",
            code: "OSA",
            country: "Spain",
            founded: 1920,
            national: false,
            logo: "https://media.api-sports.io/football/teams/727.png",
        },
        venue: {
            id: 1486,
            name: "Estadio El Sadar",
            address: "Carretera El Sadar",
            city: "Iruñea",
            capacity: 23576,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1486.png",
        },
    },
    {
        team: {
            id: 728,
            name: "Rayo Vallecano",
            code: "RAY",
            country: "Spain",
            founded: 1924,
            national: false,
            logo: "https://media.api-sports.io/football/teams/728.png",
        },
        venue: {
            id: 1488,
            name: "Estadio de Vallecas",
            address: "Calle Payaso Fofó",
            city: "Madrid",
            capacity: 15500,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1488.png",
        },
    },
    {
        team: {
            id: 797,
            name: "Elche",
            code: "ELC",
            country: "Spain",
            founded: 1923,
            national: false,
            logo: "https://media.api-sports.io/football/teams/797.png",
        },
        venue: {
            id: 1473,
            name: "Estadio Manuel Martínez Valero",
            address: "Avenida Manuel Martínez Valero 3",
            city: "Elche",
            capacity: 36017,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1473.png",
        },
    },
    {
        team: {
            id: 798,
            name: "Mallorca",
            code: "MAL",
            country: "Spain",
            founded: 1916,
            national: false,
            logo: "https://media.api-sports.io/football/teams/798.png",
        },
        venue: {
            id: 12597,
            name: "Visit Mallorca Estadi",
            address: "Camí dels Reis",
            city: "Palma de Mallorca",
            capacity: 23142,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/12597.png",
        },
    },
];

const bundesligaRaw = [
    {
        team: {
            id: 157,
            name: "Bayern Munich",
            code: "BAY",
            country: "Germany",
            founded: 1900,
            national: false,
            logo: "https://media.api-sports.io/football/teams/157.png",
        },
        venue: {
            id: 700,
            name: "Allianz Arena",
            address: "Werner-Heisenberg-Allee 25",
            city: "München",
            capacity: 75000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/700.png",
        },
    },
    {
        team: {
            id: 159,
            name: "Hertha Berlin",
            code: "HER",
            country: "Germany",
            founded: 1892,
            national: false,
            logo: "https://media.api-sports.io/football/teams/159.png",
        },
        venue: {
            id: 694,
            name: "Olympiastadion Berlin",
            address: "Olympischer Platz 3",
            city: "Berlin",
            capacity: 77116,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/694.png",
        },
    },
    {
        team: {
            id: 160,
            name: "SC Freiburg",
            code: "FRE",
            country: "Germany",
            founded: 1904,
            national: false,
            logo: "https://media.api-sports.io/football/teams/160.png",
        },
        venue: {
            id: 12717,
            name: "Europa-Park Stadion",
            address: "Achim-Stocker-Straße 1",
            city: "Freiburg im Breisgau",
            capacity: 34700,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/12717.png",
        },
    },
    {
        team: {
            id: 161,
            name: "VfL Wolfsburg",
            code: "WOL",
            country: "Germany",
            founded: 1945,
            national: false,
            logo: "https://media.api-sports.io/football/teams/161.png",
        },
        venue: {
            id: 752,
            name: "VOLKSWAGEN ARENA",
            address: "In den Allerwiesen 1",
            city: "Wolfsburg",
            capacity: 30000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/752.png",
        },
    },
    {
        team: {
            id: 162,
            name: "Werder Bremen",
            code: "WER",
            country: "Germany",
            founded: 1899,
            national: false,
            logo: "https://media.api-sports.io/football/teams/162.png",
        },
        venue: {
            id: 755,
            name: "wohninvest WESERSTADION",
            address: "Franz-Böhmert-Straße 1c",
            city: "Bremen",
            capacity: 42358,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/755.png",
        },
    },
    {
        team: {
            id: 163,
            name: "Borussia Monchengladbach",
            code: "MOE",
            country: "Germany",
            founded: 1900,
            national: false,
            logo: "https://media.api-sports.io/football/teams/163.png",
        },
        venue: {
            id: 703,
            name: "Stadion im BORUSSIA-PARK",
            address: "Hennes-Weisweiler-Allee 1",
            city: "Mönchengladbach",
            capacity: 54057,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/703.png",
        },
    },
    {
        team: {
            id: 164,
            name: "FSV Mainz 05",
            code: "MAI",
            country: "Germany",
            founded: 1905,
            national: false,
            logo: "https://media.api-sports.io/football/teams/164.png",
        },
        venue: {
            id: 11899,
            name: "MEWA ARENA",
            address: "Eugen-Salomon-Straße 1",
            city: "Mainz",
            capacity: 34034,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/11899.png",
        },
    },
    {
        team: {
            id: 165,
            name: "Borussia Dortmund",
            code: "DOR",
            country: "Germany",
            founded: 1909,
            national: false,
            logo: "https://media.api-sports.io/football/teams/165.png",
        },
        venue: {
            id: 702,
            name: "Signal-Iduna-Park",
            address: "Strobelalle 50",
            city: "Dortmund",
            capacity: 81365,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/702.png",
        },
    },
    {
        team: {
            id: 167,
            name: "1899 Hoffenheim",
            code: "HOF",
            country: "Germany",
            founded: 1899,
            national: false,
            logo: "https://media.api-sports.io/football/teams/167.png",
        },
        venue: {
            id: 724,
            name: "PreZero Arena",
            address: "Dietmar-Hopp-Straße 1",
            city: "Sinsheim",
            capacity: 30164,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/724.png",
        },
    },
    {
        team: {
            id: 168,
            name: "Bayer Leverkusen",
            code: "BAY",
            country: "Germany",
            founded: 1904,
            national: false,
            logo: "https://media.api-sports.io/football/teams/168.png",
        },
        venue: {
            id: 699,
            name: "BayArena",
            address: "Bismarckstr. 122-124",
            city: "Leverkusen",
            capacity: 30210,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/699.png",
        },
    },
    {
        team: {
            id: 169,
            name: "Eintracht Frankfurt",
            code: "EIN",
            country: "Germany",
            founded: 1899,
            national: false,
            logo: "https://media.api-sports.io/football/teams/169.png",
        },
        venue: {
            id: 10491,
            name: "Deutsche Bank Park",
            address: "Mörfelder Landstr. 362",
            city: "Frankfurt am Main",
            capacity: 52300,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/10491.png",
        },
    },
    {
        team: {
            id: 170,
            name: "FC Augsburg",
            code: "AUG",
            country: "Germany",
            founded: 1907,
            national: false,
            logo: "https://media.api-sports.io/football/teams/170.png",
        },
        venue: {
            id: 698,
            name: "WWK Arena",
            address: "Bürgermeister Ulrich-Straße 90",
            city: "Augsburg",
            capacity: 30662,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/698.png",
        },
    },
    {
        team: {
            id: 172,
            name: "VfB Stuttgart",
            code: "STU",
            country: "Germany",
            founded: 1893,
            national: false,
            logo: "https://media.api-sports.io/football/teams/172.png",
        },
        venue: {
            id: 750,
            name: "Mercedes-Benz-Arena",
            address: "Mercedesstrasse 87",
            city: "Stuttgart",
            capacity: 60469,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/750.png",
        },
    },
    {
        team: {
            id: 173,
            name: "RB Leipzig",
            code: "LEI",
            country: "Germany",
            founded: 2009,
            national: false,
            logo: "https://media.api-sports.io/football/teams/173.png",
        },
        venue: {
            id: 738,
            name: "Red Bull Arena",
            address: "Am Sportforum 3",
            city: "Leipzig",
            capacity: 47069,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/738.png",
        },
    },
    {
        team: {
            id: 174,
            name: "FC Schalke 04",
            code: "SCH",
            country: "Germany",
            founded: 1904,
            national: false,
            logo: "https://media.api-sports.io/football/teams/174.png",
        },
        venue: {
            id: 741,
            name: "VELTINS-Arena",
            address: "Arenaring 1",
            city: "Gelsenkirchen",
            capacity: 62271,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/741.png",
        },
    },
    {
        team: {
            id: 176,
            name: "VfL BOCHUM",
            code: "BOC",
            country: "Germany",
            founded: 1848,
            national: false,
            logo: "https://media.api-sports.io/football/teams/176.png",
        },
        venue: {
            id: 751,
            name: "Vonovia Ruhrstadion",
            address: "Castropher Straße 145",
            city: "Bochum",
            capacity: 30748,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/751.png",
        },
    },
    {
        team: {
            id: 182,
            name: "Union Berlin",
            code: "UNI",
            country: "Germany",
            founded: 1966,
            national: false,
            logo: "https://media.api-sports.io/football/teams/182.png",
        },
        venue: {
            id: 748,
            name: "Stadion An der Alten Försterei",
            address: "Hämmerlingstraße 80-88, Köpenick",
            city: "Berlin",
            capacity: 22467,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/748.png",
        },
    },
    {
        team: {
            id: 192,
            name: "FC Koln",
            code: "KOL",
            country: "Germany",
            founded: 1948,
            national: false,
            logo: "https://media.api-sports.io/football/teams/192.png",
        },
        venue: {
            id: 731,
            name: "RheinEnergieStadion",
            address: "Aachener Str. 999",
            city: "Köln",
            capacity: 50076,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/731.png",
        },
    },
];

const serieARaw = [
    {
        team: {
            id: 487,
            name: "Lazio",
            code: "LAZ",
            country: "Italy",
            founded: 1900,
            national: false,
            logo: "https://media.api-sports.io/football/teams/487.png",
        },
        venue: {
            id: 910,
            name: "Stadio Olimpico",
            address: "Viale dei Gladiatori, 2 / Via del Foro Italico",
            city: "Roma",
            capacity: 68530,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/910.png",
        },
    },
    {
        team: {
            id: 488,
            name: "Sassuolo",
            code: "SAS",
            country: "Italy",
            founded: 1922,
            national: false,
            logo: "https://media.api-sports.io/football/teams/488.png",
        },
        venue: {
            id: 935,
            name: "MAPEI Stadium - Città del Tricolore",
            address: "Piazza Azzuri d&apos;Italia, 1",
            city: "Reggio nell&apos;Emilia",
            capacity: 23717,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/935.png",
        },
    },
    {
        team: {
            id: 489,
            name: "AC Milan",
            code: "MIL",
            country: "Italy",
            founded: 1899,
            national: false,
            logo: "https://media.api-sports.io/football/teams/489.png",
        },
        venue: {
            id: 907,
            name: "Stadio Giuseppe Meazza",
            address: "Via Piccolomini 5",
            city: "Milano",
            capacity: 80018,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/907.png",
        },
    },
    {
        team: {
            id: 492,
            name: "Napoli",
            code: "NAP",
            country: "Italy",
            founded: 1904,
            national: false,
            logo: "https://media.api-sports.io/football/teams/492.png",
        },
        venue: {
            id: 11904,
            name: "Stadio Diego Armando Maradona",
            address: "Pizzale Vincenzo Tecchio",
            city: "Napoli",
            capacity: 60240,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/11904.png",
        },
    },
    {
        team: {
            id: 494,
            name: "Udinese",
            code: "UDI",
            country: "Italy",
            founded: 1896,
            national: false,
            logo: "https://media.api-sports.io/football/teams/494.png",
        },
        venue: {
            id: 928,
            name: "Dacia Arena",
            address: "Piazza le Repubblica Argentina, 3",
            city: "Udine",
            capacity: 25952,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/928.png",
        },
    },
    {
        team: {
            id: 496,
            name: "Juventus",
            code: "JUV",
            country: "Italy",
            founded: 1897,
            national: false,
            logo: "https://media.api-sports.io/football/teams/496.png",
        },
        venue: {
            id: 909,
            name: "Allianz Stadium",
            address: "Strada Comunale di Altessano 131",
            city: "Torino",
            capacity: 45666,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/909.png",
        },
    },
    {
        team: {
            id: 497,
            name: "AS Roma",
            code: "ROM",
            country: "Italy",
            founded: 1927,
            national: false,
            logo: "https://media.api-sports.io/football/teams/497.png",
        },
        venue: {
            id: 910,
            name: "Stadio Olimpico",
            address: "Viale dei Gladiatori, 2 / Via del Foro Italico",
            city: "Roma",
            capacity: 68530,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/910.png",
        },
    },
    {
        team: {
            id: 498,
            name: "Sampdoria",
            code: "SAM",
            country: "Italy",
            founded: 1946,
            national: false,
            logo: "https://media.api-sports.io/football/teams/498.png",
        },
        venue: {
            id: 905,
            name: "Stadio Comunale Luigi Ferraris",
            address: "Via Giovanni De Prà, 1",
            city: "Genova",
            capacity: 36703,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/905.png",
        },
    },
    {
        team: {
            id: 499,
            name: "Atalanta",
            code: "ATA",
            country: "Italy",
            founded: 1907,
            national: false,
            logo: "https://media.api-sports.io/football/teams/499.png",
        },
        venue: {
            id: 879,
            name: "Gewiss Stadium",
            address: "Viale Giulio Cesare 18",
            city: "Bergamo",
            capacity: 21300,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/879.png",
        },
    },
    {
        team: {
            id: 500,
            name: "Bologna",
            code: "BOL",
            country: "Italy",
            founded: 1909,
            national: false,
            logo: "https://media.api-sports.io/football/teams/500.png",
        },
        venue: {
            id: 881,
            name: "Stadio Renato Dall'Ara",
            address: "Via Andrea Costa, 174",
            city: "Bologna",
            capacity: 39279,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/881.png",
        },
    },
    {
        team: {
            id: 502,
            name: "Fiorentina",
            code: "FIO",
            country: "Italy",
            founded: 1926,
            national: false,
            logo: "https://media.api-sports.io/football/teams/502.png",
        },
        venue: {
            id: 902,
            name: "Stadio Artemio Franchi",
            address: "Viale Manfredo Fanti 14",
            city: "Firenze",
            capacity: 43147,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/902.png",
        },
    },
    {
        team: {
            id: 503,
            name: "Torino",
            code: "TOR",
            country: "Italy",
            founded: 1906,
            national: false,
            logo: "https://media.api-sports.io/football/teams/503.png",
        },
        venue: {
            id: 943,
            name: "Stadio Olimpico Grande Torino",
            address: "Corso Sebastopoli 123, Santa Rita",
            city: "Torino",
            capacity: 27958,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/943.png",
        },
    },
    {
        team: {
            id: 504,
            name: "Verona",
            code: "VER",
            country: "Italy",
            founded: 1903,
            national: false,
            logo: "https://media.api-sports.io/football/teams/504.png",
        },
        venue: {
            id: 890,
            name: "Stadio Marc'Antonio Bentegodi",
            address: "Piazzale Olimpia",
            city: "Verona",
            capacity: 39211,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/890.png",
        },
    },
    {
        team: {
            id: 505,
            name: "Inter",
            code: "INT",
            country: "Italy",
            founded: 1908,
            national: false,
            logo: "https://media.api-sports.io/football/teams/505.png",
        },
        venue: {
            id: 907,
            name: "Stadio Giuseppe Meazza",
            address: "Via Piccolomini 5",
            city: "Milano",
            capacity: 80018,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/907.png",
        },
    },
    {
        team: {
            id: 511,
            name: "Empoli",
            code: "EMP",
            country: "Italy",
            founded: 1920,
            national: false,
            logo: "https://media.api-sports.io/football/teams/511.png",
        },
        venue: {
            id: 896,
            name: "Stadio Carlo Castellani",
            address: "Viale delle Olimpiadi",
            city: "Empoli",
            capacity: 16284,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/896.png",
        },
    },
    {
        team: {
            id: 514,
            name: "Salernitana",
            code: "SAL",
            country: "Italy",
            founded: 2011,
            national: false,
            logo: "https://media.api-sports.io/football/teams/514.png",
        },
        venue: {
            id: 933,
            name: "Stadio Arechi",
            address: "Via Salvador Allende",
            city: "Salerno",
            capacity: 37245,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/933.png",
        },
    },
    {
        team: {
            id: 515,
            name: "Spezia",
            code: "SPE",
            country: "Italy",
            founded: 1906,
            national: false,
            logo: "https://media.api-sports.io/football/teams/515.png",
        },
        venue: {
            id: 939,
            name: "Stadio Alberto Picco",
            address: "Via Nicolò Fieschi, 18",
            city: "La Spezia",
            capacity: 11512,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/939.png",
        },
    },
    {
        team: {
            id: 520,
            name: "Cremonese",
            code: "CRE",
            country: "Italy",
            founded: 1903,
            national: false,
            logo: "https://media.api-sports.io/football/teams/520.png",
        },
        venue: {
            id: 894,
            name: "Stadio Giovanni Zini",
            address: "Via Persico, 19",
            city: "Cremona",
            capacity: 20034,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/894.png",
        },
    },
    {
        team: {
            id: 867,
            name: "Lecce",
            code: "LEC",
            country: "Italy",
            founded: 1908,
            national: false,
            logo: "https://media.api-sports.io/football/teams/867.png",
        },
        venue: {
            id: 911,
            name: "Stadio Comunale Via del Mare",
            address: "Viale dello Stadio",
            city: "Lecce",
            capacity: 33876,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/911.png",
        },
    },
    {
        team: {
            id: 1579,
            name: "Monza",
            code: "MON",
            country: "Italy",
            founded: 1912,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1579.png",
        },
        venue: {
            id: 12086,
            name: "U-Power Stadium",
            address: "Via Franco Tognini",
            city: "Monza",
            capacity: 18568,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/12086.png",
        },
    },
];

const countryCompetitionMap: Record<string, number> = {
    England: 1,
    USA: 2,
    Canada: 2,
    Spain: 3,
    Germany: 4,
    Italy: 5,
};

const raw = [
    ...eplRaw,
    ...(config.huddle.competitions.MLS ? mlsRaw : []),
    ...(config.huddle.competitions.ESP ? laLigaRaw : []),
    ...(config.huddle.competitions.ESP ? bundesligaRaw : []),
    ...(config.huddle.competitions.ESP ? serieARaw : []),
];

export const teams = raw
    .map((tData) => ({
        id: tData.team.code || "",
        code: tData.team.code || "",
        name: tData.team.name,
        logo: tData.team.logo,
        stadium: tData.venue.name,
        competition: countryCompetitionMap[tData.team.country].toString(),
    }))
    .sort((a, b) => {
        return a.name.localeCompare(b.name);
    });

export const teamSeed = raw.map((tData, idx) => ({
    id: idx + 1,
    name: tData.team.name,
    code: tData.team.code || "",
    logo: tData.team.logo,
    sport: "football" as Sport,
    sources: { apiFootball: { id: tData.team.id } },
    metadata: { stadium: tData.venue.name },
    competition: countryCompetitionMap[tData.team.country],
}));

export const teamCompetitionSeed = teamSeed.map((t) => ({
    teamId: t.id,
    competitionId: t.competition,
}));
