import { Sport } from "@prisma/client";
import { config } from "../../../../../lib/config";

const eplRaw = [
    {
        team: {
            id: 33,
            name: "Manchester United",
            code: "MUN",
            country: "England",
            founded: 1878,
            national: false,
            logo: "https://media.api-sports.io/football/teams/33.png",
        },
        venue: {
            id: 556,
            name: "Old Trafford",
            address: "Sir Matt Busby Way",
            city: "Manchester",
            capacity: 76212,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/556.png",
        },
    },
    {
        team: {
            id: 34,
            name: "Newcastle",
            code: "NEW",
            country: "England",
            founded: 1892,
            national: false,
            logo: "https://media.api-sports.io/football/teams/34.png",
        },
        venue: {
            id: 562,
            name: "St. James' Park",
            address: "St. James&apos; Street",
            city: "Newcastle upon Tyne",
            capacity: 52389,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/562.png",
        },
    },
    {
        team: {
            id: 35,
            name: "Bournemouth",
            code: "BOU",
            country: "England",
            founded: 1899,
            national: false,
            logo: "https://media.api-sports.io/football/teams/35.png",
        },
        venue: {
            id: 504,
            name: "Vitality Stadium",
            address: "Dean Court, Kings Park",
            city: "Bournemouth, Dorset",
            capacity: 12000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/504.png",
        },
    },
    {
        team: {
            id: 36,
            name: "Fulham",
            code: "FUL",
            country: "England",
            founded: 1879,
            national: false,
            logo: "https://media.api-sports.io/football/teams/36.png",
        },
        venue: {
            id: 535,
            name: "Craven Cottage",
            address: "Stevenage Road",
            city: "London",
            capacity: 25700,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/535.png",
        },
    },
    {
        team: {
            id: 39,
            name: "Wolves",
            code: "WOL",
            country: "England",
            founded: 1877,
            national: false,
            logo: "https://media.api-sports.io/football/teams/39.png",
        },
        venue: {
            id: 600,
            name: "Molineux Stadium",
            address: "Waterloo Road",
            city: "Wolverhampton, West Midlands",
            capacity: 32050,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/600.png",
        },
    },
    {
        team: {
            id: 40,
            name: "Liverpool",
            code: "LIV",
            country: "England",
            founded: 1892,
            national: false,
            logo: "https://media.api-sports.io/football/teams/40.png",
        },
        venue: {
            id: 550,
            name: "Anfield",
            address: "Anfield Road",
            city: "Liverpool",
            capacity: 55212,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/550.png",
        },
    },
    {
        team: {
            id: 41,
            name: "Southampton",
            code: "SOU",
            country: "England",
            founded: 1885,
            national: false,
            logo: "https://media.api-sports.io/football/teams/41.png",
        },
        venue: {
            id: 585,
            name: "St. Mary's Stadium",
            address: "Britannia Road",
            city: "Southampton, Hampshire",
            capacity: 32689,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/585.png",
        },
    },
    {
        team: {
            id: 42,
            name: "Arsenal",
            code: "ARS",
            country: "England",
            founded: 1886,
            national: false,
            logo: "https://media.api-sports.io/football/teams/42.png",
        },
        venue: {
            id: 494,
            name: "Emirates Stadium",
            address: "Queensland Road",
            city: "London",
            capacity: 60383,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/494.png",
        },
    },
    {
        team: {
            id: 45,
            name: "Everton",
            code: "EVE",
            country: "England",
            founded: 1878,
            national: false,
            logo: "https://media.api-sports.io/football/teams/45.png",
        },
        venue: {
            id: 8560,
            name: "Goodison Park",
            address: "Goodison Road",
            city: "Liverpool",
            capacity: 40569,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/8560.png",
        },
    },
    {
        team: {
            id: 46,
            name: "Leicester",
            code: "LEI",
            country: "England",
            founded: 1884,
            national: false,
            logo: "https://media.api-sports.io/football/teams/46.png",
        },
        venue: {
            id: 547,
            name: "King Power Stadium",
            address: "Filbert Way",
            city: "Leicester, Leicestershire",
            capacity: 34310,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/547.png",
        },
    },
    {
        team: {
            id: 47,
            name: "Tottenham",
            code: "TOT",
            country: "England",
            founded: 1882,
            national: false,
            logo: "https://media.api-sports.io/football/teams/47.png",
        },
        venue: {
            id: 593,
            name: "Tottenham Hotspur Stadium",
            address: "Bill Nicholson Way, 748 High Road",
            city: "London",
            capacity: 62062,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/593.png",
        },
    },
    {
        team: {
            id: 48,
            name: "West Ham",
            code: "WES",
            country: "England",
            founded: 1895,
            national: false,
            logo: "https://media.api-sports.io/football/teams/48.png",
        },
        venue: {
            id: 598,
            name: "London Stadium",
            address: "Marshgate Lane, Stratford",
            city: "London",
            capacity: 60000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/598.png",
        },
    },
    {
        team: {
            id: 49,
            name: "Chelsea",
            code: "CHE",
            country: "England",
            founded: 1905,
            national: false,
            logo: "https://media.api-sports.io/football/teams/49.png",
        },
        venue: {
            id: 519,
            name: "Stamford Bridge",
            address: "Fulham Road",
            city: "London",
            capacity: 41841,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/519.png",
        },
    },
    {
        team: {
            id: 50,
            name: "Manchester City",
            code: "MAC",
            country: "England",
            founded: 1880,
            national: false,
            logo: "https://media.api-sports.io/football/teams/50.png",
        },
        venue: {
            id: 555,
            name: "Etihad Stadium",
            address: "Rowsley Street",
            city: "Manchester",
            capacity: 55097,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/555.png",
        },
    },
    {
        team: {
            id: 51,
            name: "Brighton",
            code: "BRI",
            country: "England",
            founded: 1901,
            national: false,
            logo: "https://media.api-sports.io/football/teams/51.png",
        },
        venue: {
            id: 508,
            name: "The American Express Community Stadium",
            address: "Village Way",
            city: "Falmer, East Sussex",
            capacity: 31800,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/508.png",
        },
    },
    {
        team: {
            id: 52,
            name: "Crystal Palace",
            code: "CRY",
            country: "England",
            founded: 1905,
            national: false,
            logo: "https://media.api-sports.io/football/teams/52.png",
        },
        venue: {
            id: 525,
            name: "Selhurst Park",
            address: "Holmesdale Road",
            city: "London",
            capacity: 26309,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/525.png",
        },
    },
    {
        team: {
            id: 55,
            name: "Brentford",
            code: "BRE",
            country: "England",
            founded: 1889,
            national: false,
            logo: "https://media.api-sports.io/football/teams/55.png",
        },
        venue: {
            id: 10503,
            name: "Brentford Community Stadium",
            address: "166 Lionel Rd N, Brentford",
            city: "Brentford, Middlesex",
            capacity: 17250,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/10503.png",
        },
    },
    {
        team: {
            id: 63,
            name: "Leeds",
            code: "LEE",
            country: "England",
            founded: 1919,
            national: false,
            logo: "https://media.api-sports.io/football/teams/63.png",
        },
        venue: {
            id: 546,
            name: "Elland Road",
            address: "Elland Road",
            city: "Leeds, West Yorkshire",
            capacity: 40204,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/546.png",
        },
    },
    {
        team: {
            id: 65,
            name: "Nottingham Forest",
            code: "NOT",
            country: "England",
            founded: 1865,
            national: false,
            logo: "https://media.api-sports.io/football/teams/65.png",
        },
        venue: {
            id: 566,
            name: "The City Ground",
            address: "Pavilion Road",
            city: "Nottingham, Nottinghamshire",
            capacity: 30576,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/566.png",
        },
    },
    {
        team: {
            id: 66,
            name: "Aston Villa",
            code: "AST",
            country: "England",
            founded: 1874,
            national: false,
            logo: "https://media.api-sports.io/football/teams/66.png",
        },
        venue: {
            id: 495,
            name: "Villa Park",
            address: "Trinity Road",
            city: "Birmingham",
            capacity: 42788,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/495.png",
        },
    },
];

const mlsRaw = [
    {
        team: {
            id: 1595,
            name: "Seattle Sounders",
            code: "SEA",
            country: "USA",
            founded: 2007,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1595.png",
        },
        venue: {
            id: 11534,
            name: "Lumen Field",
            address: "800 Occidental Avenue South",
            city: "Seattle, Washington",
            capacity: 72000,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/11534.png",
        },
    },
    {
        team: {
            id: 1596,
            name: "San Jose Earthquakes",
            code: "JOS",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1596.png",
        },
        venue: {
            id: 11918,
            name: "PayPal Park",
            address: "1123 Coleman Avenue",
            city: "San Jose, California",
            capacity: 18000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/11918.png",
        },
    },
    {
        team: {
            id: 1597,
            name: "FC Dallas",
            code: "DAL",
            country: "USA",
            founded: 1996,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1597.png",
        },
        venue: {
            id: 1612,
            name: "Toyota Stadium",
            address: "6000 Main Street",
            city: "Frisco, Texas",
            capacity: 22565,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1612.png",
        },
    },
    {
        team: {
            id: 1598,
            name: "Orlando City SC",
            code: "ORL",
            country: "USA",
            founded: 2008,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1598.png",
        },
        venue: {
            id: 1838,
            name: "Exploria Stadium",
            address: "655 West Church Street",
            city: "Orlando, Florida",
            capacity: 25527,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1838.png",
        },
    },
    {
        team: {
            id: 1599,
            name: "Philadelphia Union",
            code: "PHI",
            country: "USA",
            founded: 2008,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1599.png",
        },
        venue: {
            id: 1620,
            name: "Subaru Park",
            address: "Seaport Drive",
            city: "Chester, Pennsylvania",
            capacity: 19487,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1620.png",
        },
    },
    {
        team: {
            id: 1600,
            name: "Houston Dynamo",
            code: "HOU",
            country: "USA",
            founded: 2005,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1600.png",
        },
        venue: {
            id: 12599,
            name: "PNC Stadium",
            address: "2200 Texas Avenue, East End",
            city: "Houston, Texas",
            capacity: 22661,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/12599.png",
        },
    },
    {
        team: {
            id: 1601,
            name: "Toronto FC",
            code: "TOR",
            country: "Canada",
            founded: 2006,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1601.png",
        },
        venue: {
            id: 312,
            name: "BMO Field",
            address: "170 Princes’ Boulevard",
            city: "Toronto, Ontario",
            capacity: 36045,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/312.png",
        },
    },
    {
        team: {
            id: 1602,
            name: "New York Red Bulls",
            code: "YOR",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1602.png",
        },
        venue: {
            id: 1619,
            name: "Red Bull Arena",
            address: "Frank Rogers Boulevard South",
            city: "Harrison, New Jersey",
            capacity: 26765,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1619.png",
        },
    },
    {
        team: {
            id: 1603,
            name: "Vancouver Whitecaps",
            code: "VAN",
            country: "Canada",
            founded: 1986,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1603.png",
        },
        venue: {
            id: 313,
            name: "BC Place Stadium",
            address: "777 Pacific Boulevard, False Creek",
            city: "Vancouver, British Columbia",
            capacity: 59687,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/313.png",
        },
    },
    {
        team: {
            id: 1604,
            name: "New York City FC",
            code: "NYC",
            country: "USA",
            founded: 2013,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1604.png",
        },
        venue: {
            id: 1833,
            name: "Yankee Stadium",
            address: "One East 161st Street, The Bronx",
            city: "New York City",
            capacity: 54251,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1833.png",
        },
    },
    {
        team: {
            id: 1605,
            name: "Los Angeles Galaxy",
            code: "ANG",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1605.png",
        },
        venue: {
            id: 1616,
            name: "Dignity Health Sports Park",
            address: "18400 Avalon Boulevard, Dominguez Hills",
            city: "Carson, California",
            capacity: 30510,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1616.png",
        },
    },
    {
        team: {
            id: 1606,
            name: "Real Salt Lake",
            code: "SAL",
            country: "USA",
            founded: 2004,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1606.png",
        },
        venue: {
            id: 1621,
            name: "Rio Tinto Stadium",
            address: "9256 South State Street",
            city: "Sandy, Utah",
            capacity: 21363,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1621.png",
        },
    },
    {
        team: {
            id: 1607,
            name: "Chicago Fire",
            code: "CHI",
            country: "USA",
            founded: 1997,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1607.png",
        },
        venue: {
            id: 1609,
            name: "Soldier Field",
            address: "1410 South Museum Campus Drive",
            city: "Chicago, Illinois",
            capacity: 62493,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1609.png",
        },
    },
    {
        team: {
            id: 1608,
            name: "Atlanta United FC",
            code: "ATL",
            country: "USA",
            founded: 2014,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1608.png",
        },
        venue: {
            id: 1898,
            name: "Mercedes-Benz Stadium",
            address: "1 AMB Drive North West",
            city: "Atlanta, Georgia",
            capacity: 73019,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/1898.png",
        },
    },
    {
        team: {
            id: 1609,
            name: "New England Revolution",
            code: "ENG",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1609.png",
        },
        venue: {
            id: 1618,
            name: "Gillette Stadium",
            address: "1388 One Patriot Place",
            city: "Foxborough, Massachusetts",
            capacity: 68756,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/1618.png",
        },
    },
    {
        team: {
            id: 1610,
            name: "Colorado Rapids",
            code: "COL",
            country: "USA",
            founded: 1996,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1610.png",
        },
        venue: {
            id: 1610,
            name: "Dick's Sporting Goods Park",
            address: "6000 Victory Way, Commerce City",
            city: "Denver, Colorado",
            capacity: 19734,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1610.png",
        },
    },
    {
        team: {
            id: 1611,
            name: "Sporting Kansas City",
            code: "KAN",
            country: "USA",
            founded: 1995,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1611.png",
        },
        venue: {
            id: 1615,
            name: "Children's Mercy Park",
            address: "One Sporting Way",
            city: "Kansas City, Kansas",
            capacity: 21650,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1615.png",
        },
    },
    {
        team: {
            id: 1612,
            name: "Minnesota United FC",
            code: "MIN",
            country: "USA",
            founded: 2010,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1612.png",
        },
        venue: {
            id: 1617,
            name: "Allianz Field",
            address: "400 Snelling Avenue North",
            city: "Saint Paul, Minnesota",
            capacity: 19939,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1617.png",
        },
    },
    {
        team: {
            id: 1613,
            name: "Columbus Crew",
            code: "COL",
            country: "USA",
            founded: 1996,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1613.png",
        },
        venue: {
            id: 12667,
            name: "Lower.com Field",
            address: "560 West Nationwide Boulevard",
            city: "Columbus, Ohio",
            capacity: 20407,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/12667.png",
        },
    },
    {
        team: {
            id: 1614,
            name: "Montreal Impact",
            code: "MON",
            country: "Canada",
            founded: 2010,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1614.png",
        },
        venue: {
            id: 310,
            name: "Stade Saputo",
            address: "4750, rue Sherbrooke Est",
            city: "Montreal, Quebec",
            capacity: 20801,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/310.png",
        },
    },
    {
        team: {
            id: 1615,
            name: "DC United",
            code: "UNI",
            country: "USA",
            founded: 1996,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1615.png",
        },
        venue: {
            id: 1613,
            name: "Audi Field",
            address: "32-60 R Street South West, Buzzard Point",
            city: "Washington, District of Columbia",
            capacity: 20600,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1613.png",
        },
    },
    {
        team: {
            id: 1616,
            name: "Los Angeles FC",
            code: "LAFC",
            country: "USA",
            founded: 2014,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1616.png",
        },
        venue: {
            id: 1922,
            name: "Banc of California Stadium",
            address: "3939 S Figueroa Street",
            city: "Los Angeles, California",
            capacity: 22902,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/1922.png",
        },
    },
    {
        team: {
            id: 1617,
            name: "Portland Timbers",
            code: "POR",
            country: "USA",
            founded: 2009,
            national: false,
            logo: "https://media.api-sports.io/football/teams/1617.png",
        },
        venue: {
            id: 1748,
            name: "Providence Park",
            address: "1844 SW Morrison Street",
            city: "Portland, Oregon",
            capacity: 25518,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/1748.png",
        },
    },
    {
        team: {
            id: 2242,
            name: "FC Cincinnati",
            code: "CIN",
            country: "USA",
            founded: null,
            national: false,
            logo: "https://media.api-sports.io/football/teams/2242.png",
        },
        venue: {
            id: 3076,
            name: "Nippert Stadium",
            address: "2700 Bearcats Way",
            city: "Cincinnati, Ohio",
            capacity: 40000,
            surface: "artificial turf",
            image: "https://media.api-sports.io/football/venues/3076.png",
        },
    },
    {
        team: {
            id: 9568,
            name: "Inter Miami",
            code: "MIA",
            country: "USA",
            founded: 2018,
            national: false,
            logo: "https://media.api-sports.io/football/teams/9568.png",
        },
        venue: {
            id: 11976,
            name: "DRV PNK Stadium",
            address: "1350 Northwest 55th Street",
            city: "Fort Lauderdale, Florida",
            capacity: 18535,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/11976.png",
        },
    },
    {
        team: {
            id: 9569,
            name: "Nashville SC",
            code: "NSH",
            country: "USA",
            founded: 2020,
            national: false,
            logo: "https://media.api-sports.io/football/teams/9569.png",
        },
        venue: {
            id: 12697,
            name: "Nashville SC Stadium",
            address: "513 Benton Avenue",
            city: "Nashville, Tennessee",
            capacity: 30000,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/12697.png",
        },
    },
    {
        team: {
            id: 16489,
            name: "Austin",
            code: "ATX",
            country: "USA",
            founded: 2021,
            national: false,
            logo: "https://media.api-sports.io/football/teams/16489.png",
        },
        venue: {
            id: 11535,
            name: "Q2 Stadium",
            address: "10414 Mc Kalla Place",
            city: "Austin, Texas",
            capacity: 20738,
            surface: "grass",
            image: "https://media.api-sports.io/football/venues/11535.png",
        },
    },
    {
        team: {
            id: 18310,
            name: "Charlotte",
            code: "CLT",
            country: "USA",
            founded: null,
            national: false,
            logo: "https://media.api-sports.io/football/teams/18310.png",
        },
        venue: {
            id: null,
            name: null,
            address: null,
            city: null,
            capacity: null,
            surface: null,
            image: null,
        },
    },
];

const raw = [...eplRaw, ...(config.huddle.competitions.MLS ? mlsRaw : [])];

export const teams = raw
    .map((tData) => ({
        id: tData.team.code || "",
        code: tData.team.code || "",
        name: tData.team.name,
        logo: tData.team.logo,
        stadium: tData.venue.name,
        competition: tData.team.country === "USA" ? "MLS" : "EPL",
    }))
    .sort((a, b) => {
        return a.name.localeCompare(b.name);
    });

export const teamSeed = raw.map((tData, idx) => ({
    id: idx + 1,
    name: tData.team.name,
    code: tData.team.code || "",
    logo: tData.team.logo,
    sport: "football" as Sport,
    sources: { apiFootball: { id: tData.team.id } },
    metadata: { stadium: tData.venue.name },
    competition: tData.team.country === "USA" ? "MLS" : "EPL",
}));

export const teamCompetitionSeed = teamSeed.map((t) => ({
    teamId: t.id,
    competitionId: t.competition === "EPL" ? 1 : 2,
}));
